/**
 * FULL QUESTION BANK (300 Questions Total)
 * - 100 Learning Style Questions (Kolb)
 * - 100 Thinking Style Questions (Sternberg)
 * - 100 Decision Style Questions (Dual-Process)
 * 
 * Each set evenly distributed across style quadrants/subtypes
 */

// ============= A. KOLB LEARNING STYLES (100 QUESTIONS) =============
// 25 questions per quadrant: Diverging, Assimilating, Converging, Accommodating

export const kolbQuestions = [
  // DIVERGING (25 Questions: 1-25)
  { id: 1, question: "I enjoy exploring ideas from multiple angles.", style: "Diverging", points: 1 },
  { id: 2, question: "I like observing situations before participating.", style: "Diverging", points: 1 },
  { id: 3, question: "I learn best through watching others.", style: "Diverging", points: 1 },
  { id: 4, question: "I prefer group discussions over lectures.", style: "Diverging", points: 1 },
  { id: 5, question: "I take time to reflect before acting.", style: "Diverging", points: 1 },
  { id: 6, question: "I enjoy imagining different outcomes.", style: "Diverging", points: 1 },
  { id: 7, question: "I prefer creative tasks to technical ones.", style: "Diverging", points: 1 },
  { id: 8, question: "I like listening more than speaking.", style: "Diverging", points: 1 },
  { id: 9, question: "I enjoy brainstorming sessions.", style: "Diverging", points: 1 },
  { id: 10, question: "I like learning from real-life stories.", style: "Diverging", points: 1 },
  { id: 11, question: "I notice small details others miss.", style: "Diverging", points: 1 },
  { id: 12, question: "I enjoy drawing, sketching, or visualizing.", style: "Diverging", points: 1 },
  { id: 13, question: "I like connecting ideas together.", style: "Diverging", points: 1 },
  { id: 14, question: "I enjoy thinking about \"what if\" scenarios.", style: "Diverging", points: 1 },
  { id: 15, question: "I prefer to understand people's feelings when learning.", style: "Diverging", points: 1 },
  { id: 16, question: "I like exploring possibilities.", style: "Diverging", points: 1 },
  { id: 17, question: "I enjoy open-ended tasks.", style: "Diverging", points: 1 },
  { id: 18, question: "I learn well when I can observe first.", style: "Diverging", points: 1 },
  { id: 19, question: "I enjoy using my imagination.", style: "Diverging", points: 1 },
  { id: 20, question: "I like reflecting on experiences before deciding.", style: "Diverging", points: 1 },
  { id: 21, question: "I prefer having choices in how to learn.", style: "Diverging", points: 1 },
  { id: 22, question: "I enjoy group creativity exercises.", style: "Diverging", points: 1 },
  { id: 23, question: "I like taking time to think deeply.", style: "Diverging", points: 1 },
  { id: 24, question: "I enjoy understanding how things relate.", style: "Diverging", points: 1 },
  { id: 25, question: "I prefer learning visually (diagrams, maps, images).", style: "Diverging", points: 1 },

  // ASSIMILATING (25 Questions: 26-50)
  { id: 26, question: "I prefer learning through reading and listening.", style: "Assimilating", points: 1 },
  { id: 27, question: "I enjoy organizing information.", style: "Assimilating", points: 1 },
  { id: 28, question: "I like clear explanations.", style: "Assimilating", points: 1 },
  { id: 29, question: "I often ask \"why\" something works.", style: "Assimilating", points: 1 },
  { id: 30, question: "I enjoy working with theories.", style: "Assimilating", points: 1 },
  { id: 31, question: "I prefer structured lessons.", style: "Assimilating", points: 1 },
  { id: 32, question: "I enjoy analyzing information step-by-step.", style: "Assimilating", points: 1 },
  { id: 33, question: "I like understanding big ideas before details.", style: "Assimilating", points: 1 },
  { id: 34, question: "I enjoy solving logical problems.", style: "Assimilating", points: 1 },
  { id: 35, question: "I like following instructions.", style: "Assimilating", points: 1 },
  { id: 36, question: "I prefer factual information.", style: "Assimilating", points: 1 },
  { id: 37, question: "I like charts, graphs, and models.", style: "Assimilating", points: 1 },
  { id: 38, question: "I enjoy comparing different ideas.", style: "Assimilating", points: 1 },
  { id: 39, question: "I enjoy subjects that require deep thinking.", style: "Assimilating", points: 1 },
  { id: 40, question: "I like identifying patterns.", style: "Assimilating", points: 1 },
  { id: 41, question: "I enjoy reading to understand concepts.", style: "Assimilating", points: 1 },
  { id: 42, question: "I prefer teachers who give clear explanations.", style: "Assimilating", points: 1 },
  { id: 43, question: "I like connecting facts into meaningful ideas.", style: "Assimilating", points: 1 },
  { id: 44, question: "I learn best through structured methods.", style: "Assimilating", points: 1 },
  { id: 45, question: "I enjoy summarizing information.", style: "Assimilating", points: 1 },
  { id: 46, question: "I prefer thinking quietly rather than discussing.", style: "Assimilating", points: 1 },
  { id: 47, question: "I like understanding how things fit together.", style: "Assimilating", points: 1 },
  { id: 48, question: "I enjoy research and investigation.", style: "Assimilating", points: 1 },
  { id: 49, question: "I prefer logic over emotion.", style: "Assimilating", points: 1 },
  { id: 50, question: "I enjoy building organized notes.", style: "Assimilating", points: 1 },

  // CONVERGING (25 Questions: 51-75)
  { id: 51, question: "I like finding practical solutions.", style: "Converging", points: 1 },
  { id: 52, question: "I enjoy solving problems independently.", style: "Converging", points: 1 },
  { id: 53, question: "I enjoy hands-on experiments.", style: "Converging", points: 1 },
  { id: 54, question: "I prefer technical tasks.", style: "Converging", points: 1 },
  { id: 55, question: "I like figuring out how things work.", style: "Converging", points: 1 },
  { id: 56, question: "I enjoy using tools, models, or simulations.", style: "Converging", points: 1 },
  { id: 57, question: "I prefer clear goals and tasks.", style: "Converging", points: 1 },
  { id: 58, question: "I enjoy challenges that require problem-solving.", style: "Converging", points: 1 },
  { id: 59, question: "I like applying ideas in real-life situations.", style: "Converging", points: 1 },
  { id: 60, question: "I enjoy using step-by-step methods.", style: "Converging", points: 1 },
  { id: 61, question: "I like testing different solutions.", style: "Converging", points: 1 },
  { id: 62, question: "I prefer working alone on tasks.", style: "Converging", points: 1 },
  { id: 63, question: "I enjoy using technology to learn.", style: "Converging", points: 1 },
  { id: 64, question: "I like fixing things.", style: "Converging", points: 1 },
  { id: 65, question: "I enjoy projects with specific outcomes.", style: "Converging", points: 1 },
  { id: 66, question: "I like learning through trial and error.", style: "Converging", points: 1 },
  { id: 67, question: "I prefer structured problem-solving.", style: "Converging", points: 1 },
  { id: 68, question: "I enjoy tasks where I can produce results.", style: "Converging", points: 1 },
  { id: 69, question: "I like experimenting with ideas.", style: "Converging", points: 1 },
  { id: 70, question: "I enjoy tasks that involve logic and reasoning.", style: "Converging", points: 1 },
  { id: 71, question: "I like focusing on one best solution.", style: "Converging", points: 1 },
  { id: 72, question: "I enjoy competitive tasks.", style: "Converging", points: 1 },
  { id: 73, question: "I prefer subjects that involve clear answers.", style: "Converging", points: 1 },
  { id: 74, question: "I like following strategies that work.", style: "Converging", points: 1 },
  { id: 75, question: "I prefer tasks that require accuracy.", style: "Converging", points: 1 },

  // ACCOMMODATING (25 Questions: 76-100)
  { id: 76, question: "I enjoy learning by doing.", style: "Accommodating", points: 1 },
  { id: 77, question: "I like trying new things.", style: "Accommodating", points: 1 },
  { id: 78, question: "I enjoy taking risks in learning.", style: "Accommodating", points: 1 },
  { id: 79, question: "I prefer activities over reading.", style: "Accommodating", points: 1 },
  { id: 80, question: "I enjoy group work.", style: "Accommodating", points: 1 },
  { id: 81, question: "I make decisions based on feelings.", style: "Accommodating", points: 1 },
  { id: 82, question: "I enjoy adapting to new situations.", style: "Accommodating", points: 1 },
  { id: 83, question: "I like learning through trial and error.", style: "Accommodating", points: 1 },
  { id: 84, question: "I prefer hands-on experiences.", style: "Accommodating", points: 1 },
  { id: 85, question: "I like taking action quickly.", style: "Accommodating", points: 1 },
  { id: 86, question: "I enjoy leading group activities.", style: "Accommodating", points: 1 },
  { id: 87, question: "I prefer flexible tasks.", style: "Accommodating", points: 1 },
  { id: 88, question: "I enjoy learning through games.", style: "Accommodating", points: 1 },
  { id: 89, question: "I like working on new and exciting ideas.", style: "Accommodating", points: 1 },
  { id: 90, question: "I enjoy real-life challenges.", style: "Accommodating", points: 1 },
  { id: 91, question: "I prefer learning with others.", style: "Accommodating", points: 1 },
  { id: 92, question: "I like spontaneous activities.", style: "Accommodating", points: 1 },
  { id: 93, question: "I enjoy using intuition when learning.", style: "Accommodating", points: 1 },
  { id: 94, question: "I like trying different approaches.", style: "Accommodating", points: 1 },
  { id: 95, question: "I learn best by participating actively.", style: "Accommodating", points: 1 },
  { id: 96, question: "I enjoy subjects with movement and activity.", style: "Accommodating", points: 1 },
  { id: 97, question: "I like exploring new environments.", style: "Accommodating", points: 1 },
  { id: 98, question: "I enjoy outdoor or field activities.", style: "Accommodating", points: 1 },
  { id: 99, question: "I prefer to learn first and reflect later.", style: "Accommodating", points: 1 },
  { id: 100, question: "I enjoy fast-paced, action-based tasks.", style: "Accommodating", points: 1 }
];

// ============= B. STERNBERG THINKING STYLES (100 QUESTIONS) =============
// 34 Analytical, 33 Creative, 33 Practical (balanced distribution)

export const sternbergQuestions = [
  // ANALYTICAL THINKING (34 Questions: 1-34)
  // Logic, evaluation, comparison, analysis
  { id: 1, question: "I enjoy solving problems with clear right or wrong answers.", style: "Analytical", points: 1 },
  { id: 2, question: "I like finding mistakes and fixing them.", style: "Analytical", points: 1 },
  { id: 3, question: "I question information to see if it makes sense.", style: "Analytical", points: 1 },
  { id: 4, question: "I enjoy comparing two ideas to see which is better.", style: "Analytical", points: 1 },
  { id: 5, question: "I like looking for clues in difficult questions.", style: "Analytical", points: 1 },
  { id: 6, question: "I understand things better when I break them into smaller parts.", style: "Analytical", points: 1 },
  { id: 7, question: "I enjoy working with numbers or graphs.", style: "Analytical", points: 1 },
  { id: 8, question: "I check facts before believing them.", style: "Analytical", points: 1 },
  { id: 9, question: "I think deeply before choosing an answer.", style: "Analytical", points: 1 },
  { id: 10, question: "I enjoy puzzles like Sudoku or math challenges.", style: "Analytical", points: 1 },
  { id: 11, question: "I like finding patterns in schoolwork or activities.", style: "Analytical", points: 1 },
  { id: 12, question: "I analyze situations before acting.", style: "Analytical", points: 1 },
  { id: 13, question: "I enjoy answering questions that require explanations.", style: "Analytical", points: 1 },
  { id: 14, question: "I like thinking about the reasons why things happen.", style: "Analytical", points: 1 },
  { id: 15, question: "I enjoy choosing the best solution out of many options.", style: "Analytical", points: 1 },
  { id: 16, question: "I solve problems step-by-step.", style: "Analytical", points: 1 },
  { id: 17, question: "I enjoy difficult academic tasks.", style: "Analytical", points: 1 },
  { id: 18, question: "I check my work carefully for mistakes.", style: "Analytical", points: 1 },
  { id: 19, question: "I compare different options before deciding.", style: "Analytical", points: 1 },
  { id: 20, question: "I enjoy subjects like math and science.", style: "Analytical", points: 1 },
  { id: 21, question: "I like following logical steps to solve problems.", style: "Analytical", points: 1 },
  { id: 22, question: "I think about cause and effect in situations.", style: "Analytical", points: 1 },
  { id: 23, question: "I notice small details others might miss.", style: "Analytical", points: 1 },
  { id: 24, question: "I enjoy analyzing charts or diagrams.", style: "Analytical", points: 1 },
  { id: 25, question: "I like explaining why an answer is correct.", style: "Analytical", points: 1 },
  { id: 26, question: "I enjoy evaluating whether statements are true or false.", style: "Analytical", points: 1 },
  { id: 27, question: "I spot weaknesses in arguments easily.", style: "Analytical", points: 1 },
  { id: 28, question: "I think about consequences before making decisions.", style: "Analytical", points: 1 },
  { id: 29, question: "I enjoy logical debates or discussions.", style: "Analytical", points: 1 },
  { id: 30, question: "I question things that do not make sense.", style: "Analytical", points: 1 },
  { id: 31, question: "I like tasks that require careful thinking.", style: "Analytical", points: 1 },
  { id: 32, question: "I predict outcomes based on evidence.", style: "Analytical", points: 1 },
  { id: 33, question: "I compare facts to understand a situation better.", style: "Analytical", points: 1 },
  { id: 34, question: "I enjoy analyzing stories to find deeper meanings.", style: "Analytical", points: 1 },

  // CREATIVE THINKING (33 Questions: 35-67)
  // Imagination, innovation, originality, divergent thinking
  { id: 35, question: "I enjoy coming up with new ideas.", style: "Creative", points: 1 },
  { id: 36, question: "I like imagining different possibilities.", style: "Creative", points: 1 },
  { id: 37, question: "I enjoy drawing, writing, or creating things.", style: "Creative", points: 1 },
  { id: 38, question: "I think of ideas that others might not consider.", style: "Creative", points: 1 },
  { id: 39, question: "I like making up stories or scenarios.", style: "Creative", points: 1 },
  { id: 40, question: "I enjoy exploring unusual or surprising solutions.", style: "Creative", points: 1 },
  { id: 41, question: "I ask \"What if?\" questions often.", style: "Creative", points: 1 },
  { id: 42, question: "I enjoy brainstorming sessions.", style: "Creative", points: 1 },
  { id: 43, question: "I like tasks that allow free imagination.", style: "Creative", points: 1 },
  { id: 44, question: "I enjoy inventing new ways of doing things.", style: "Creative", points: 1 },
  { id: 45, question: "I try to connect unrelated ideas together.", style: "Creative", points: 1 },
  { id: 46, question: "I feel excited when I discover a new idea.", style: "Creative", points: 1 },
  { id: 47, question: "I imagine different outcomes to situations.", style: "Creative", points: 1 },
  { id: 48, question: "I enjoy activities where there is no single correct answer.", style: "Creative", points: 1 },
  { id: 49, question: "I like designing things such as posters, projects, or games.", style: "Creative", points: 1 },
  { id: 50, question: "I enjoy humor and creative jokes.", style: "Creative", points: 1 },
  { id: 51, question: "I enjoy thinking outside the box.", style: "Creative", points: 1 },
  { id: 52, question: "I imagine improvements to things I use every day.", style: "Creative", points: 1 },
  { id: 53, question: "I enjoy expressing my ideas through art or writing.", style: "Creative", points: 1 },
  { id: 54, question: "I create solutions that seem unusual but effective.", style: "Creative", points: 1 },
  { id: 55, question: "I enjoy exploring new experiences or places.", style: "Creative", points: 1 },
  { id: 56, question: "I think creatively when faced with a problem.", style: "Creative", points: 1 },
  { id: 57, question: "I feel confident sharing unique ideas with others.", style: "Creative", points: 1 },
  { id: 58, question: "I combine simple ideas to make bigger or better ideas.", style: "Creative", points: 1 },
  { id: 59, question: "I like challenges that require imagination.", style: "Creative", points: 1 },
  { id: 60, question: "I enjoy experimenting with different ways to express myself.", style: "Creative", points: 1 },
  { id: 61, question: "I can turn small ideas into creative projects.", style: "Creative", points: 1 },
  { id: 62, question: "I enjoy inventing things or imagining inventions.", style: "Creative", points: 1 },
  { id: 63, question: "I like adding my personal style to my work.", style: "Creative", points: 1 },
  { id: 64, question: "I enjoy rewriting or reimagining stories.", style: "Creative", points: 1 },
  { id: 65, question: "I can think of creative shortcuts in tasks.", style: "Creative", points: 1 },
  { id: 66, question: "I enjoy daydreaming new ideas.", style: "Creative", points: 1 },
  { id: 67, question: "I see possibilities where others see problems.", style: "Creative", points: 1 },

  // PRACTICAL THINKING (33 Questions: 68-100)
  // Real-life problem solving, adaptability, common sense
  { id: 68, question: "I like solving real-life problems.", style: "Practical", points: 1 },
  { id: 69, question: "I use common sense to figure things out.", style: "Practical", points: 1 },
  { id: 70, question: "I enjoy fixing things around me.", style: "Practical", points: 1 },
  { id: 71, question: "I can solve problems without needing full instructions.", style: "Practical", points: 1 },
  { id: 72, question: "I understand how to use information in real life.", style: "Practical", points: 1 },
  { id: 73, question: "I organize my tasks to get things done easily.", style: "Practical", points: 1 },
  { id: 74, question: "I make plans that are realistic and achievable.", style: "Practical", points: 1 },
  { id: 75, question: "I know how to use tools or resources around me.", style: "Practical", points: 1 },
  { id: 76, question: "I focus on solutions that work, not just theories.", style: "Practical", points: 1 },
  { id: 77, question: "I enjoy helping others solve everyday problems.", style: "Practical", points: 1 },
  { id: 78, question: "I can explain things in simple words.", style: "Practical", points: 1 },
  { id: 79, question: "I learn quickly from real experiences.", style: "Practical", points: 1 },
  { id: 80, question: "I like developing practical solutions.", style: "Practical", points: 1 },
  { id: 81, question: "I enjoy tasks that show real-life results.", style: "Practical", points: 1 },
  { id: 82, question: "I find ways to complete tasks efficiently.", style: "Practical", points: 1 },
  { id: 83, question: "I know how to manage my time well.", style: "Practical", points: 1 },
  { id: 84, question: "I make decisions based on what is doable.", style: "Practical", points: 1 },
  { id: 85, question: "I think of ways to improve everyday routines.", style: "Practical", points: 1 },
  { id: 86, question: "I understand how to apply rules to real situations.", style: "Practical", points: 1 },
  { id: 87, question: "I prefer steps that lead directly to success.", style: "Practical", points: 1 },
  { id: 88, question: "I look for good shortcuts when solving problems.", style: "Practical", points: 1 },
  { id: 89, question: "I enjoy using technology to solve problems.", style: "Practical", points: 1 },
  { id: 90, question: "I know how to tell what is urgent and what can wait.", style: "Practical", points: 1 },
  { id: 91, question: "I adjust quickly when plans change.", style: "Practical", points: 1 },
  { id: 92, question: "I think about consequences before acting.", style: "Practical", points: 1 },
  { id: 93, question: "I know how to get help when I need it.", style: "Practical", points: 1 },
  { id: 94, question: "I stay calm in real-life challenges.", style: "Practical", points: 1 },
  { id: 95, question: "I enjoy tasks that require organizing or planning.", style: "Practical", points: 1 },
  { id: 96, question: "I know how to avoid simple mistakes in daily tasks.", style: "Practical", points: 1 },
  { id: 97, question: "I like planning solutions that people can use easily.", style: "Practical", points: 1 },
  { id: 98, question: "I solve problems based on real experiences.", style: "Practical", points: 1 },
  { id: 99, question: "I find ways to make tasks easier or faster.", style: "Practical", points: 1 },
  { id: 100, question: "I enjoy hands-on activities that solve real problems.", style: "Practical", points: 1 }
];

// ============= C. DUAL-PROCESS DECISION STYLES (100 QUESTIONS) =============
// 50 Intuitive (System 1), 50 Reflective (System 2)

export const dualProcessQuestions = [
  // INTUITIVE / SYSTEM 1 (50 Questions: 1-50)
  // Fast, instinctive, emotional, immediate responses
  { id: 1, question: "I often make decisions quickly.", style: "Intuitive", points: 1 },
  { id: 2, question: "I trust my first instinct.", style: "Intuitive", points: 1 },
  { id: 3, question: "I choose answers based on what feels right.", style: "Intuitive", points: 1 },
  { id: 4, question: "I react fast in unexpected situations.", style: "Intuitive", points: 1 },
  { id: 5, question: "I make decisions without overthinking.", style: "Intuitive", points: 1 },
  { id: 6, question: "I follow my gut feelings.", style: "Intuitive", points: 1 },
  { id: 7, question: "I enjoy fast-paced challenges.", style: "Intuitive", points: 1 },
  { id: 8, question: "I decide quickly during group work.", style: "Intuitive", points: 1 },
  { id: 9, question: "I can guess answers confidently.", style: "Intuitive", points: 1 },
  { id: 10, question: "I rely on intuition when I'm unsure.", style: "Intuitive", points: 1 },
  { id: 11, question: "I act immediately when I notice a problem.", style: "Intuitive", points: 1 },
  { id: 12, question: "I enjoy games that require quick reactions.", style: "Intuitive", points: 1 },
  { id: 13, question: "I prefer simple and quick solutions.", style: "Intuitive", points: 1 },
  { id: 14, question: "I make choices without hesitating too much.", style: "Intuitive", points: 1 },
  { id: 15, question: "I trust my experience over long explanations.", style: "Intuitive", points: 1 },
  { id: 16, question: "I respond quickly in conversations.", style: "Intuitive", points: 1 },
  { id: 17, question: "I like fast decision-making tasks.", style: "Intuitive", points: 1 },
  { id: 18, question: "I dislike long explanations before acting.", style: "Intuitive", points: 1 },
  { id: 19, question: "I sometimes decide before hearing all the details.", style: "Intuitive", points: 1 },
  { id: 20, question: "I follow the option that feels natural.", style: "Intuitive", points: 1 },
  { id: 21, question: "I choose the easiest-looking option first.", style: "Intuitive", points: 1 },
  { id: 22, question: "I notice things quickly and respond right away.", style: "Intuitive", points: 1 },
  { id: 23, question: "I make quick judgments about situations.", style: "Intuitive", points: 1 },
  { id: 24, question: "I act fast in emergencies.", style: "Intuitive", points: 1 },
  { id: 25, question: "I react quickly when playing games or sports.", style: "Intuitive", points: 1 },
  { id: 26, question: "I choose answers that \"sound right.\"", style: "Intuitive", points: 1 },
  { id: 27, question: "I decide quickly in simple choices like snacks or games.", style: "Intuitive", points: 1 },
  { id: 28, question: "I rely on memory rather than analysis.", style: "Intuitive", points: 1 },
  { id: 29, question: "I feel confident making fast decisions.", style: "Intuitive", points: 1 },
  { id: 30, question: "I enjoy taking risks based on how I feel.", style: "Intuitive", points: 1 },
  { id: 31, question: "I sometimes act before planning.", style: "Intuitive", points: 1 },
  { id: 32, question: "I rely on past patterns when deciding.", style: "Intuitive", points: 1 },
  { id: 33, question: "I trust familiar solutions.", style: "Intuitive", points: 1 },
  { id: 34, question: "I avoid spending too much time thinking.", style: "Intuitive", points: 1 },
  { id: 35, question: "I enjoy exciting and fast choices.", style: "Intuitive", points: 1 },
  { id: 36, question: "I rely more on instinct than instructions.", style: "Intuitive", points: 1 },
  { id: 37, question: "I choose quickly when taking tests.", style: "Intuitive", points: 1 },
  { id: 38, question: "I prefer quick problem-solving.", style: "Intuitive", points: 1 },
  { id: 39, question: "I respond emotionally to situations.", style: "Intuitive", points: 1 },
  { id: 40, question: "I follow what feels right emotionally.", style: "Intuitive", points: 1 },
  { id: 41, question: "I trust quick impressions of people.", style: "Intuitive", points: 1 },
  { id: 42, question: "I choose the first idea that comes to mind.", style: "Intuitive", points: 1 },
  { id: 43, question: "I enjoy tasks that require quick decisions.", style: "Intuitive", points: 1 },
  { id: 44, question: "I dislike slow, detailed work.", style: "Intuitive", points: 1 },
  { id: 45, question: "I decide quickly when I feel confident.", style: "Intuitive", points: 1 },
  { id: 46, question: "I react instantly when something happens.", style: "Intuitive", points: 1 },
  { id: 47, question: "I choose based on what looks easiest.", style: "Intuitive", points: 1 },
  { id: 48, question: "I sometimes solve problems by guessing.", style: "Intuitive", points: 1 },
  { id: 49, question: "I enjoy making fast choices.", style: "Intuitive", points: 1 },
  { id: 50, question: "I often know what to do without thinking much.", style: "Intuitive", points: 1 },

  // REFLECTIVE / SYSTEM 2 (50 Questions: 51-100)
  // Logical, slow, step-by-step, effortful processing
  { id: 51, question: "I take time to think before making decisions.", style: "Reflective", points: 1 },
  { id: 52, question: "I like checking information before acting.", style: "Reflective", points: 1 },
  { id: 53, question: "I consider all options carefully.", style: "Reflective", points: 1 },
  { id: 54, question: "I analyze problems step-by-step.", style: "Reflective", points: 1 },
  { id: 55, question: "I double-check information before drawing conclusions.", style: "Reflective", points: 1 },
  { id: 56, question: "I think about long-term consequences.", style: "Reflective", points: 1 },
  { id: 57, question: "I enjoy solving problems that require deep thinking.", style: "Reflective", points: 1 },
  { id: 58, question: "I prefer detailed explanations before deciding.", style: "Reflective", points: 1 },
  { id: 59, question: "I understand better when I reflect slowly.", style: "Reflective", points: 1 },
  { id: 60, question: "I choose answers after evaluating all evidence.", style: "Reflective", points: 1 },
  { id: 61, question: "I like researching before making choices.", style: "Reflective", points: 1 },
  { id: 62, question: "I avoid rushing decisions.", style: "Reflective", points: 1 },
  { id: 63, question: "I plan before starting tasks.", style: "Reflective", points: 1 },
  { id: 64, question: "I weigh the pros and cons before deciding.", style: "Reflective", points: 1 },
  { id: 65, question: "I take time to understand instructions fully.", style: "Reflective", points: 1 },
  { id: 66, question: "I consider how my decisions affect others.", style: "Reflective", points: 1 },
  { id: 67, question: "I think carefully before speaking.", style: "Reflective", points: 1 },
  { id: 68, question: "I enjoy analyzing choices.", style: "Reflective", points: 1 },
  { id: 69, question: "I check facts before accepting them.", style: "Reflective", points: 1 },
  { id: 70, question: "I solve problems logically.", style: "Reflective", points: 1 },
  { id: 71, question: "I ask questions when I don't understand.", style: "Reflective", points: 1 },
  { id: 72, question: "I organize my thoughts before choosing.", style: "Reflective", points: 1 },
  { id: 73, question: "I study details before deciding.", style: "Reflective", points: 1 },
  { id: 74, question: "I review my work before submitting it.", style: "Reflective", points: 1 },
  { id: 75, question: "I reflect on past decisions to improve.", style: "Reflective", points: 1 },
  { id: 76, question: "I prefer planned routines over spontaneous actions.", style: "Reflective", points: 1 },
  { id: 77, question: "I base my choices on reasoning.", style: "Reflective", points: 1 },
  { id: 78, question: "I avoid guessing if I can think it through.", style: "Reflective", points: 1 },
  { id: 79, question: "I evaluate evidence carefully.", style: "Reflective", points: 1 },
  { id: 80, question: "I think of different alternatives first.", style: "Reflective", points: 1 },
  { id: 81, question: "I prefer slow, thoughtful tasks.", style: "Reflective", points: 1 },
  { id: 82, question: "I reconsider decisions when new information appears.", style: "Reflective", points: 1 },
  { id: 83, question: "I break big decisions into smaller steps.", style: "Reflective", points: 1 },
  { id: 84, question: "I make decisions based on facts, not feelings.", style: "Reflective", points: 1 },
  { id: 85, question: "I solve problems by thinking deeply.", style: "Reflective", points: 1 },
  { id: 86, question: "I enjoy tasks that require careful thinking.", style: "Reflective", points: 1 },
  { id: 87, question: "I check my understanding before moving on.", style: "Reflective", points: 1 },
  { id: 88, question: "I think about possible outcomes before acting.", style: "Reflective", points: 1 },
  { id: 89, question: "I like understanding the full picture before choosing.", style: "Reflective", points: 1 },
  { id: 90, question: "I take time to gather all details.", style: "Reflective", points: 1 },
  { id: 91, question: "I prefer being certain before acting.", style: "Reflective", points: 1 },
  { id: 92, question: "I plan ahead when I know something is coming.", style: "Reflective", points: 1 },
  { id: 93, question: "I think twice before making a choice.", style: "Reflective", points: 1 },
  { id: 94, question: "I avoid taking shortcuts in important tasks.", style: "Reflective", points: 1 },
  { id: 95, question: "I make decisions based on logic.", style: "Reflective", points: 1 },
  { id: 96, question: "I analyze instructions carefully.", style: "Reflective", points: 1 },
  { id: 97, question: "I think before responding in conversations.", style: "Reflective", points: 1 },
  { id: 98, question: "I solve problems more carefully than quickly.", style: "Reflective", points: 1 },
  { id: 99, question: "I prefer accuracy over speed.", style: "Reflective", points: 1 },
  { id: 100, question: "I rely on step-by-step thinking when solving problems.", style: "Reflective", points: 1 }
];