/**
 * APPROVED KIDS ASSESSMENT QUESTIONS (Ages 6-10)
 * 
 * Format:
 * - 1 short sentence ("I..." statement)
 * - 1 picture (to be added)
 * - 3-emoji answers: 😊 (Yes, like me) / 😐 (Sometimes) / ☹ (Not really)
 * 
 * Total: 500 questions across 5 categories
 * - Problem-Solving (100): Q1-100
 * - Decision-Making (100): Q101-200
 * - Social Thinking (100): Q201-300
 * - Motivation (100): Q301-400
 * - Attention & Behaviour (100): Q401-500
 */

export interface ApprovedKidsQuestion {
  id: number;
  text: string;
  category: 'problem-solving' | 'decision-making' | 'social-thinking' | 'motivation' | 'attention-behaviour';
  pictureUrl?: string; // To be added when illustrations available
}

export const EMOJI_RESPONSES = {
  YES: { emoji: '😊', label: 'Yes, like me', value: 3 },
  SOMETIMES: { emoji: '😐', label: 'Sometimes', value: 2 },
  NO: { emoji: '☹', label: 'Not really', value: 1 }
} as const;

// PROBLEM-SOLVING (100 questions: Q1-Q100)
export const problemSolvingQuestions: ApprovedKidsQuestion[] = [
  { id: 1, text: "I try to fix things myself.", category: 'problem-solving' },
  { id: 2, text: "I keep trying when something is hard.", category: 'problem-solving' },
  { id: 3, text: "I like figuring things out.", category: 'problem-solving' },
  { id: 4, text: "I try new ways when I get stuck.", category: 'problem-solving' },
  { id: 5, text: "I look carefully before choosing.", category: 'problem-solving' },
  { id: 6, text: "I try again when I make a mistake.", category: 'problem-solving' },
  { id: 7, text: "I think about what might work best.", category: 'problem-solving' },
  { id: 8, text: "I check what the problem is first.", category: 'problem-solving' },
  { id: 9, text: "I try to solve problems step by step.", category: 'problem-solving' },
  { id: 10, text: "I ask for clues when I don't understand.", category: 'problem-solving' },
  { id: 11, text: "I stay calm when solving a hard task.", category: 'problem-solving' },
  { id: 12, text: "I look closely to see what went wrong.", category: 'problem-solving' },
  { id: 13, text: "I try one idea, then another.", category: 'problem-solving' },
  { id: 14, text: "I use items around me to help me solve things.", category: 'problem-solving' },
  { id: 15, text: "I try to understand the whole problem.", category: 'problem-solving' },
  { id: 16, text: "I fix small mistakes by myself.", category: 'problem-solving' },
  { id: 17, text: "I think about the problem before starting.", category: 'problem-solving' },
  { id: 18, text: "I try different ways to finish a task.", category: 'problem-solving' },
  { id: 19, text: "I try again even when I feel frustrated.", category: 'problem-solving' },
  { id: 20, text: "I try a new plan if the first one doesn't work.", category: 'problem-solving' },
  { id: 21, text: "I take my time to get things right.", category: 'problem-solving' },
  { id: 22, text: "I think about what happened last time.", category: 'problem-solving' },
  { id: 23, text: "I look for patterns to help me solve things.", category: 'problem-solving' },
  { id: 24, text: "I try to remember things that worked before.", category: 'problem-solving' },
  { id: 25, text: "I try not to give up quickly.", category: 'problem-solving' },
  { id: 26, text: "I check my work to see if it's correct.", category: 'problem-solving' },
  { id: 27, text: "I think before I ask for help.", category: 'problem-solving' },
  { id: 28, text: "I try to understand why something didn't work.", category: 'problem-solving' },
  { id: 29, text: "I try to finish a problem on my own.", category: 'problem-solving' },
  { id: 30, text: "I try to fix toys or things gently.", category: 'problem-solving' },
  { id: 31, text: "I try to build things in different ways.", category: 'problem-solving' },
  { id: 32, text: "I look for hints in my work.", category: 'problem-solving' },
  { id: 33, text: "I use simple steps to solve problems.", category: 'problem-solving' },
  { id: 34, text: "I try again even when it's confusing.", category: 'problem-solving' },
  { id: 35, text: "I watch others fix things to learn.", category: 'problem-solving' },
  { id: 36, text: "I try to guess answers using clues.", category: 'problem-solving' },
  { id: 37, text: "I think about what could happen next.", category: 'problem-solving' },
  { id: 38, text: "I notice small things that help me solve problems.", category: 'problem-solving' },
  { id: 39, text: "I use my hands to figure things out.", category: 'problem-solving' },
  { id: 40, text: "I try to finish a puzzle even when it's tough.", category: 'problem-solving' },
  { id: 41, text: "I change my plan if I need to.", category: 'problem-solving' },
  { id: 42, text: "I take a deep breath when stuck.", category: 'problem-solving' },
  { id: 43, text: "I try to stay focused until I solve it.", category: 'problem-solving' },
  { id: 44, text: "I think of different ways to use objects.", category: 'problem-solving' },
  { id: 45, text: "I look again when I don't understand.", category: 'problem-solving' },
  { id: 46, text: "I think quietly before choosing.", category: 'problem-solving' },
  { id: 47, text: "I check my answers to see if they make sense.", category: 'problem-solving' },
  { id: 48, text: "I try things one step at a time.", category: 'problem-solving' },
  { id: 49, text: "I try harder when it is difficult.", category: 'problem-solving' },
  { id: 50, text: "I think about what tools can help me.", category: 'problem-solving' },
  { id: 51, text: "I use pictures to help me solve problems.", category: 'problem-solving' },
  { id: 52, text: "I try to imagine the answer in my head.", category: 'problem-solving' },
  { id: 53, text: "I ask good questions to understand better.", category: 'problem-solving' },
  { id: 54, text: "I look around for helpful clues.", category: 'problem-solving' },
  { id: 55, text: "I try a new method when my old one fails.", category: 'problem-solving' },
  { id: 56, text: "I check each step of my work.", category: 'problem-solving' },
  { id: 57, text: "I think of simple ways to solve things.", category: 'problem-solving' },
  { id: 58, text: "I enjoy solving puzzles.", category: 'problem-solving' },
  { id: 59, text: "I think about what might happen if I try something.", category: 'problem-solving' },
  { id: 60, text: "I look at the whole problem before starting.", category: 'problem-solving' },
  { id: 61, text: "I try to stay patient when confused.", category: 'problem-solving' },
  { id: 62, text: "I use both my hands and my brain to figure things out.", category: 'problem-solving' },
  { id: 63, text: "I try to solve problems with what I have.", category: 'problem-solving' },
  { id: 64, text: "I try to understand why the answer works.", category: 'problem-solving' },
  { id: 65, text: "I try my best not to rush.", category: 'problem-solving' },
  { id: 66, text: "I think about how to make things easier.", category: 'problem-solving' },
  { id: 67, text: "I notice when something doesn't fit or match.", category: 'problem-solving' },
  { id: 68, text: "I enjoy finding solutions.", category: 'problem-solving' },
  { id: 69, text: "I try to make smart guesses.", category: 'problem-solving' },
  { id: 70, text: "I like trying new ideas.", category: 'problem-solving' },
  { id: 71, text: "I think about the steps I need.", category: 'problem-solving' },
  { id: 72, text: "I try again after taking a break.", category: 'problem-solving' },
  { id: 73, text: "I try to fix mistakes without getting upset.", category: 'problem-solving' },
  { id: 74, text: "I think about which choice is better.", category: 'problem-solving' },
  { id: 75, text: "I try to finish tasks even when they're long.", category: 'problem-solving' },
  { id: 76, text: "I look for help only after trying first.", category: 'problem-solving' },
  { id: 77, text: "I think of reasons why something didn't work.", category: 'problem-solving' },
  { id: 78, text: "I use my eyes and hands together to solve problems.", category: 'problem-solving' },
  { id: 79, text: "I try to solve problems in my own way.", category: 'problem-solving' },
  { id: 80, text: "I break big tasks into small ones.", category: 'problem-solving' },
  { id: 81, text: "I try to stay calm when stuck.", category: 'problem-solving' },
  { id: 82, text: "I think before I act.", category: 'problem-solving' },
  { id: 83, text: "I look again if I didn't see something right.", category: 'problem-solving' },
  { id: 84, text: "I try different shapes and ways to build things.", category: 'problem-solving' },
  { id: 85, text: "I check if my idea works.", category: 'problem-solving' },
  { id: 86, text: "I think of better ways to finish work.", category: 'problem-solving' },
  { id: 87, text: "I like seeing how things fit together.", category: 'problem-solving' },
  { id: 88, text: "I enjoy trying new challenges.", category: 'problem-solving' },
  { id: 89, text: "I learn from my mistakes.", category: 'problem-solving' },
  { id: 90, text: "I try to figure out problems on paper.", category: 'problem-solving' },
  { id: 91, text: "I try to understand a problem fully.", category: 'problem-solving' },
  { id: 92, text: "I think of what I need before starting.", category: 'problem-solving' },
  { id: 93, text: "I try again even when others finish first.", category: 'problem-solving' },
  { id: 94, text: "I try to see what part of the problem is hard.", category: 'problem-solving' },
  { id: 95, text: "I keep trying even when it's slow.", category: 'problem-solving' },
  { id: 96, text: "I look for details that can help me.", category: 'problem-solving' },
  { id: 97, text: "I use hints from teachers to solve things.", category: 'problem-solving' },
  { id: 98, text: "I take time to think of answers.", category: 'problem-solving' },
  { id: 99, text: "I rethink my plan if needed.", category: 'problem-solving' },
  { id: 100, text: "I try to finish problems with confidence.", category: 'problem-solving' }
];

// DECISION-MAKING (100 questions: Q101-Q200)
export const decisionMakingQuestions: ApprovedKidsQuestion[] = [
  { id: 101, text: "I choose quickly when I know the answer.", category: 'decision-making' },
  { id: 102, text: "I think a little before choosing.", category: 'decision-making' },
  { id: 103, text: "I ask for help when I'm unsure.", category: 'decision-making' },
  { id: 104, text: "I check again to be sure.", category: 'decision-making' },
  { id: 105, text: "I plan what to do first.", category: 'decision-making' },
  { id: 106, text: "I pick what feels right to me.", category: 'decision-making' },
  { id: 107, text: "I choose carefully when it's important.", category: 'decision-making' },
  { id: 108, text: "I decide after thinking about my choices.", category: 'decision-making' },
  { id: 109, text: "I ask questions when I don't understand.", category: 'decision-making' },
  { id: 110, text: "I choose the option that looks safest.", category: 'decision-making' },
  { id: 111, text: "I decide what to do before starting.", category: 'decision-making' },
  { id: 112, text: "I change my mind if I learn something new.", category: 'decision-making' },
  { id: 113, text: "I think about what will happen next.", category: 'decision-making' },
  { id: 114, text: "I choose the best idea I can.", category: 'decision-making' },
  { id: 115, text: "I listen before deciding.", category: 'decision-making' },
  { id: 116, text: "I wait my turn to decide.", category: 'decision-making' },
  { id: 117, text: "I decide slowly when something is hard.", category: 'decision-making' },
  { id: 118, text: "I think about what's fair.", category: 'decision-making' },
  { id: 119, text: "I decide what to try first.", category: 'decision-making' },
  { id: 120, text: "I ask someone to explain a choice if I'm confused.", category: 'decision-making' },
  { id: 121, text: "I decide again if my idea doesn't work.", category: 'decision-making' },
  { id: 122, text: "I check if my choice is okay.", category: 'decision-making' },
  { id: 123, text: "I choose by thinking of what helps most.", category: 'decision-making' },
  { id: 124, text: "I think about other people before choosing.", category: 'decision-making' },
  { id: 125, text: "I try my best to make good choices.", category: 'decision-making' },
  { id: 126, text: "I pick a choice I understand well.", category: 'decision-making' },
  { id: 127, text: "I decide only after listening to all sides.", category: 'decision-making' },
  { id: 128, text: "I choose what makes sense.", category: 'decision-making' },
  { id: 129, text: "I try not to rush my choices.", category: 'decision-making' },
  { id: 130, text: "I decide after thinking of two or more ideas.", category: 'decision-making' },
  { id: 131, text: "I think of what might go wrong.", category: 'decision-making' },
  { id: 132, text: "I think of what might go right.", category: 'decision-making' },
  { id: 133, text: "I choose the idea that solves the problem.", category: 'decision-making' },
  { id: 134, text: "I decide what to do when no one tells me.", category: 'decision-making' },
  { id: 135, text: "I think about what is allowed before choosing.", category: 'decision-making' },
  { id: 136, text: "I choose after asking myself \"Is this good?\"", category: 'decision-making' },
  { id: 137, text: "I think quietly before I choose.", category: 'decision-making' },
  { id: 138, text: "I decide based on what I know.", category: 'decision-making' },
  { id: 139, text: "I try not to copy others when choosing.", category: 'decision-making' },
  { id: 140, text: "I choose what helps me learn.", category: 'decision-making' },
  { id: 141, text: "I choose calmly even when others rush.", category: 'decision-making' },
  { id: 142, text: "I check if my choice is the same as the instructions.", category: 'decision-making' },
  { id: 143, text: "I decide again if I made a mistake.", category: 'decision-making' },
  { id: 144, text: "I choose what feels comfortable.", category: 'decision-making' },
  { id: 145, text: "I think about past choices before deciding now.", category: 'decision-making' },
  { id: 146, text: "I decide what tools I need before working.", category: 'decision-making' },
  { id: 147, text: "I choose what is right even when it's hard.", category: 'decision-making' },
  { id: 148, text: "I try to make choices that are kind.", category: 'decision-making' },
  { id: 149, text: "I think about what is true.", category: 'decision-making' },
  { id: 150, text: "I choose by thinking of simple steps.", category: 'decision-making' },
  { id: 151, text: "I decide using what I remember.", category: 'decision-making' },
  { id: 152, text: "I check my choice with a teacher if needed.", category: 'decision-making' },
  { id: 153, text: "I decide what order to do things in.", category: 'decision-making' },
  { id: 154, text: "I choose what helps me finish on time.", category: 'decision-making' },
  { id: 155, text: "I decide using clues I notice.", category: 'decision-making' },
  { id: 156, text: "I change my choice when I find a better idea.", category: 'decision-making' },
  { id: 157, text: "I think of the rule before choosing.", category: 'decision-making' },
  { id: 158, text: "I think of the reason before choosing.", category: 'decision-making' },
  { id: 159, text: "I choose what helps me stay safe.", category: 'decision-making' },
  { id: 160, text: "I decide what will make me proud.", category: 'decision-making' },
  { id: 161, text: "I choose what will help me get along with others.", category: 'decision-making' },
  { id: 162, text: "I decide after thinking quietly.", category: 'decision-making' },
  { id: 163, text: "I choose ideas one by one until something works.", category: 'decision-making' },
  { id: 164, text: "I decide how much time I need.", category: 'decision-making' },
  { id: 165, text: "I choose which task to finish first.", category: 'decision-making' },
  { id: 166, text: "I think about the smallest step I can start with.", category: 'decision-making' },
  { id: 167, text: "I decide how to fix small problems.", category: 'decision-making' },
  { id: 168, text: "I choose what keeps me calm.", category: 'decision-making' },
  { id: 169, text: "I decide how to keep things fair.", category: 'decision-making' },
  { id: 170, text: "I choose what helps everyone.", category: 'decision-making' },
  { id: 171, text: "I think of what I learned before choosing.", category: 'decision-making' },
  { id: 172, text: "I decide what makes learning easier.", category: 'decision-making' },
  { id: 173, text: "I choose kindly when friends want different things.", category: 'decision-making' },
  { id: 174, text: "I decide after listening carefully.", category: 'decision-making' },
  { id: 175, text: "I choose what I understand best.", category: 'decision-making' },
  { id: 176, text: "I decide using ideas I trust.", category: 'decision-making' },
  { id: 177, text: "I check if my choice follows the rule.", category: 'decision-making' },
  { id: 178, text: "I choose something new when old ways don't work.", category: 'decision-making' },
  { id: 179, text: "I think about the time before choosing.", category: 'decision-making' },
  { id: 180, text: "I choose what keeps me focused.", category: 'decision-making' },
  { id: 181, text: "I decide how to share fairly.", category: 'decision-making' },
  { id: 182, text: "I pick what helps me finish safely.", category: 'decision-making' },
  { id: 183, text: "I choose the option that helps me improve.", category: 'decision-making' },
  { id: 184, text: "I decide to rest when I need to.", category: 'decision-making' },
  { id: 185, text: "I choose what will help me succeed.", category: 'decision-making' },
  { id: 186, text: "I decide by thinking slowly.", category: 'decision-making' },
  { id: 187, text: "I choose again if I feel unsure.", category: 'decision-making' },
  { id: 188, text: "I decide who to ask for help.", category: 'decision-making' },
  { id: 189, text: "I choose the easiest step to start with.", category: 'decision-making' },
  { id: 190, text: "I decide where to sit so I can learn.", category: 'decision-making' },
  { id: 191, text: "I choose what helps me follow directions.", category: 'decision-making' },
  { id: 192, text: "I decide when it's better to wait.", category: 'decision-making' },
  { id: 193, text: "I choose what keeps the peace.", category: 'decision-making' },
  { id: 194, text: "I think \"Is this the right choice?\" before choosing.", category: 'decision-making' },
  { id: 195, text: "I decide based on what I know is right.", category: 'decision-making' },
  { id: 196, text: "I choose what helps me finish the task.", category: 'decision-making' },
  { id: 197, text: "I choose ideas that help the group.", category: 'decision-making' },
  { id: 198, text: "I think first, then choose.", category: 'decision-making' },
  { id: 199, text: "I decide how to be responsible.", category: 'decision-making' },
  { id: 200, text: "I choose what is good for me and others.", category: 'decision-making' }
];

// SOCIAL THINKING (100 questions: Q201-Q300)
export const socialThinkingQuestions: ApprovedKidsQuestion[] = [
  { id: 201, text: "I listen to friends.", category: 'social-thinking' },
  { id: 202, text: "I wait my turn.", category: 'social-thinking' },
  { id: 203, text: "I help others.", category: 'social-thinking' },
  { id: 204, text: "I solve problems with friends.", category: 'social-thinking' },
  { id: 205, text: "I stay calm when disagreed with.", category: 'social-thinking' },
  { id: 206, text: "I share toys and materials.", category: 'social-thinking' },
  { id: 207, text: "I use kind words with others.", category: 'social-thinking' },
  { id: 208, text: "I try to understand how others feel.", category: 'social-thinking' },
  { id: 209, text: "I ask friends how they are doing.", category: 'social-thinking' },
  { id: 210, text: "I give others a chance to speak.", category: 'social-thinking' },
  { id: 211, text: "I listen when someone talks to me.", category: 'social-thinking' },
  { id: 212, text: "I say \"sorry\" when I hurt someone.", category: 'social-thinking' },
  { id: 213, text: "I share ideas during group work.", category: 'social-thinking' },
  { id: 214, text: "I play fairly with others.", category: 'social-thinking' },
  { id: 215, text: "I try to make others feel included.", category: 'social-thinking' },
  { id: 216, text: "I wait for my turn to talk.", category: 'social-thinking' },
  { id: 217, text: "I follow group rules.", category: 'social-thinking' },
  { id: 218, text: "I try to solve small fights peacefully.", category: 'social-thinking' },
  { id: 219, text: "I try to make new friends.", category: 'social-thinking' },
  { id: 220, text: "I help someone who needs support.", category: 'social-thinking' },
  { id: 221, text: "I listen carefully during group time.", category: 'social-thinking' },
  { id: 222, text: "I show respect to classmates.", category: 'social-thinking' },
  { id: 223, text: "I try not to interrupt others.", category: 'social-thinking' },
  { id: 224, text: "I say \"please\" and \"thank you.\"", category: 'social-thinking' },
  { id: 225, text: "I work well with partners.", category: 'social-thinking' },
  { id: 226, text: "I ask others if they want to join in.", category: 'social-thinking' },
  { id: 227, text: "I give compliments to others.", category: 'social-thinking' },
  { id: 228, text: "I try to cheer up a sad friend.", category: 'social-thinking' },
  { id: 229, text: "I talk calmly during disagreements.", category: 'social-thinking' },
  { id: 230, text: "I let others pick sometimes.", category: 'social-thinking' },
  { id: 231, text: "I ask before taking someone's things.", category: 'social-thinking' },
  { id: 232, text: "I try to understand others' points of view.", category: 'social-thinking' },
  { id: 233, text: "I follow instructions in a group.", category: 'social-thinking' },
  { id: 234, text: "I take turns during games.", category: 'social-thinking' },
  { id: 235, text: "I let others share their ideas too.", category: 'social-thinking' },
  { id: 236, text: "I use a quiet voice when needed.", category: 'social-thinking' },
  { id: 237, text: "I treat others the way I want to be treated.", category: 'social-thinking' },
  { id: 238, text: "I try to be patient with friends.", category: 'social-thinking' },
  { id: 239, text: "I ask for help when a problem is too big.", category: 'social-thinking' },
  { id: 240, text: "I include people who feel left out.", category: 'social-thinking' },
  { id: 241, text: "I try to keep peace between friends.", category: 'social-thinking' },
  { id: 242, text: "I use gentle hands when playing.", category: 'social-thinking' },
  { id: 243, text: "I speak politely to teachers and classmates.", category: 'social-thinking' },
  { id: 244, text: "I respect other people's space.", category: 'social-thinking' },
  { id: 245, text: "I cooperate during group work.", category: 'social-thinking' },
  { id: 246, text: "I say how I feel without shouting.", category: 'social-thinking' },
  { id: 247, text: "I listen to people's ideas even if they differ.", category: 'social-thinking' },
  { id: 248, text: "I try to stop arguments by talking calmly.", category: 'social-thinking' },
  { id: 249, text: "I check if someone needs help.", category: 'social-thinking' },
  { id: 250, text: "I hold the door for others.", category: 'social-thinking' },
  { id: 251, text: "I help clean up after activities.", category: 'social-thinking' },
  { id: 252, text: "I include others in my games.", category: 'social-thinking' },
  { id: 253, text: "I follow classroom routines with others.", category: 'social-thinking' },
  { id: 254, text: "I try to be a good friend.", category: 'social-thinking' },
  { id: 255, text: "I apologize when I make mistakes.", category: 'social-thinking' },
  { id: 256, text: "I try to be gentle with everyone.", category: 'social-thinking' },
  { id: 257, text: "I let others have a turn with toys.", category: 'social-thinking' },
  { id: 258, text: "I smile and greet people.", category: 'social-thinking' },
  { id: 259, text: "I try not to tease others.", category: 'social-thinking' },
  { id: 260, text: "I use kind hands and feet.", category: 'social-thinking' },
  { id: 261, text: "I ask friends what they like.", category: 'social-thinking' },
  { id: 262, text: "I listen to others' opinions.", category: 'social-thinking' },
  { id: 263, text: "I stay calm during group work.", category: 'social-thinking' },
  { id: 264, text: "I talk nicely when someone disagrees.", category: 'social-thinking' },
  { id: 265, text: "I use words instead of shouting.", category: 'social-thinking' },
  { id: 266, text: "I try to solve problems with talking.", category: 'social-thinking' },
  { id: 267, text: "I treat everyone with kindness.", category: 'social-thinking' },
  { id: 268, text: "I work together even when the task is tough.", category: 'social-thinking' },
  { id: 269, text: "I notice when someone is upset.", category: 'social-thinking' },
  { id: 270, text: "I ask permission before joining a game.", category: 'social-thinking' },
  { id: 271, text: "I speak kindly about others.", category: 'social-thinking' },
  { id: 272, text: "I try to understand why someone is upset.", category: 'social-thinking' },
  { id: 273, text: "I help solve misunderstandings.", category: 'social-thinking' },
  { id: 274, text: "I share classroom materials.", category: 'social-thinking' },
  { id: 275, text: "I avoid arguments when possible.", category: 'social-thinking' },
  { id: 276, text: "I use calm words to fix problems.", category: 'social-thinking' },
  { id: 277, text: "I show respect even when I don't agree.", category: 'social-thinking' },
  { id: 278, text: "I take responsibility for my actions.", category: 'social-thinking' },
  { id: 279, text: "I check if someone wants to play alone.", category: 'social-thinking' },
  { id: 280, text: "I ask before borrowing things.", category: 'social-thinking' },
  { id: 281, text: "I try to make new students feel welcome.", category: 'social-thinking' },
  { id: 282, text: "I sit quietly when others need quiet.", category: 'social-thinking' },
  { id: 283, text: "I raise my hand before speaking.", category: 'social-thinking' },
  { id: 284, text: "I play kindly during group activities.", category: 'social-thinking' },
  { id: 285, text: "I wait for others to finish speaking.", category: 'social-thinking' },
  { id: 286, text: "I think before I speak.", category: 'social-thinking' },
  { id: 287, text: "I treat classmates kindly even on bad days.", category: 'social-thinking' },
  { id: 288, text: "I talk slowly when someone is confused.", category: 'social-thinking' },
  { id: 289, text: "I stay calm even when I'm upset.", category: 'social-thinking' },
  { id: 290, text: "I accept when others want something different.", category: 'social-thinking' },
  { id: 291, text: "I respect classmates' belongings.", category: 'social-thinking' },
  { id: 292, text: "I give others time to think.", category: 'social-thinking' },
  { id: 293, text: "I work well even with new people.", category: 'social-thinking' },
  { id: 294, text: "I try not to blame others quickly.", category: 'social-thinking' },
  { id: 295, text: "I take turns during activities.", category: 'social-thinking' },
  { id: 296, text: "I do my part in group tasks.", category: 'social-thinking' },
  { id: 297, text: "I try to settle problems without fighting.", category: 'social-thinking' },
  { id: 298, text: "I tell adults when a problem is too big.", category: 'social-thinking' },
  { id: 299, text: "I encourage others during work.", category: 'social-thinking' },
  { id: 300, text: "I show kindness to everyone in class.", category: 'social-thinking' }
];

// MOTIVATION (100 questions: Q301-Q400)
export const motivationQuestions: ApprovedKidsQuestion[] = [
  { id: 301, text: "I try new things.", category: 'motivation' },
  { id: 302, text: "I start work by myself.", category: 'motivation' },
  { id: 303, text: "I finish what I start.", category: 'motivation' },
  { id: 304, text: "I try again after mistakes.", category: 'motivation' },
  { id: 305, text: "I like learning new things.", category: 'motivation' },
  { id: 306, text: "I try even when something feels scary.", category: 'motivation' },
  { id: 307, text: "I keep going when a task feels long.", category: 'motivation' },
  { id: 308, text: "I try my best, even on hard days.", category: 'motivation' },
  { id: 309, text: "I feel proud when I try my hardest.", category: 'motivation' },
  { id: 310, text: "I want to improve at things I learn.", category: 'motivation' },
  { id: 311, text: "I try to do better each time.", category: 'motivation' },
  { id: 312, text: "I get excited to learn something new.", category: 'motivation' },
  { id: 313, text: "I try something again until I understand it.", category: 'motivation' },
  { id: 314, text: "I try to do work neatly.", category: 'motivation' },
  { id: 315, text: "I want to learn more every day.", category: 'motivation' },
  { id: 316, text: "I feel happy when I complete a task.", category: 'motivation' },
  { id: 317, text: "I like trying new activities.", category: 'motivation' },
  { id: 318, text: "I try to stay focused on my work.", category: 'motivation' },
  { id: 319, text: "I enjoy learning new skills.", category: 'motivation' },
  { id: 320, text: "I try to set small goals for myself.", category: 'motivation' },
  { id: 321, text: "I keep working even when I feel tired.", category: 'motivation' },
  { id: 322, text: "I try not to give up quickly.", category: 'motivation' },
  { id: 323, text: "I want to get better at things I find hard.", category: 'motivation' },
  { id: 324, text: "I feel good when I solve a problem.", category: 'motivation' },
  { id: 325, text: "I try tasks even if no one asks me to.", category: 'motivation' },
  { id: 326, text: "I push myself to do my best.", category: 'motivation' },
  { id: 327, text: "I get excited to show what I learned.", category: 'motivation' },
  { id: 328, text: "I try things that are challenging.", category: 'motivation' },
  { id: 329, text: "I feel proud when I complete hard work.", category: 'motivation' },
  { id: 330, text: "I don't stop when something gets tricky.", category: 'motivation' },
  { id: 331, text: "I enjoy learning with a purpose.", category: 'motivation' },
  { id: 332, text: "I try new things even if I'm unsure.", category: 'motivation' },
  { id: 333, text: "I like finishing assignments early.", category: 'motivation' },
  { id: 334, text: "I want to become smarter.", category: 'motivation' },
  { id: 335, text: "I feel motivated when I see progress.", category: 'motivation' },
  { id: 336, text: "I try again even after failing.", category: 'motivation' },
  { id: 337, text: "I want to understand difficult ideas.", category: 'motivation' },
  { id: 338, text: "I try to listen carefully when learning.", category: 'motivation' },
  { id: 339, text: "I like setting goals for myself.", category: 'motivation' },
  { id: 340, text: "I try to do things better than before.", category: 'motivation' },
  { id: 341, text: "I enjoy discovering new information.", category: 'motivation' },
  { id: 342, text: "I try my best even when I'm slow.", category: 'motivation' },
  { id: 343, text: "I challenge myself to learn more.", category: 'motivation' },
  { id: 344, text: "I try to stay positive when learning.", category: 'motivation' },
  { id: 345, text: "I keep trying even if others finish faster.", category: 'motivation' },
  { id: 346, text: "I enjoy learning from mistakes.", category: 'motivation' },
  { id: 347, text: "I try to finish tasks without being reminded.", category: 'motivation' },
  { id: 348, text: "I feel happy when I work hard.", category: 'motivation' },
  { id: 349, text: "I try my best in every subject.", category: 'motivation' },
  { id: 350, text: "I enjoy completing projects.", category: 'motivation' },
  { id: 351, text: "I try to focus even when I'm excited.", category: 'motivation' },
  { id: 352, text: "I like learning through practice.", category: 'motivation' },
  { id: 353, text: "I try my best even if no one is watching.", category: 'motivation' },
  { id: 354, text: "I work hard when I want to improve.", category: 'motivation' },
  { id: 355, text: "I feel proud when I don't give up.", category: 'motivation' },
  { id: 356, text: "I try to learn something new every week.", category: 'motivation' },
  { id: 357, text: "I enjoy working on challenges.", category: 'motivation' },
  { id: 358, text: "I keep trying even when others give up.", category: 'motivation' },
  { id: 359, text: "I like improving my skills.", category: 'motivation' },
  { id: 360, text: "I try to be better today than yesterday.", category: 'motivation' },
  { id: 361, text: "I feel good when I reach my goals.", category: 'motivation' },
  { id: 362, text: "I try to keep my mind on my work.", category: 'motivation' },
  { id: 363, text: "I work hard to finish what I start.", category: 'motivation' },
  { id: 364, text: "I try again until I understand.", category: 'motivation' },
  { id: 365, text: "I like seeing myself get better.", category: 'motivation' },
  { id: 366, text: "I try to complete tasks on time.", category: 'motivation' },
  { id: 367, text: "I enjoy learning quietly.", category: 'motivation' },
  { id: 368, text: "I motivate myself to finish tasks.", category: 'motivation' },
  { id: 369, text: "I try hard on things I enjoy.", category: 'motivation' },
  { id: 370, text: "I try hard on things I don't enjoy too.", category: 'motivation' },
  { id: 371, text: "I feel happy when teachers say I tried well.", category: 'motivation' },
  { id: 372, text: "I enjoy staying focused on good work.", category: 'motivation' },
  { id: 373, text: "I try to learn even when I'm tired.", category: 'motivation' },
  { id: 374, text: "I challenge myself to think harder.", category: 'motivation' },
  { id: 375, text: "I try to push myself gently.", category: 'motivation' },
  { id: 376, text: "I like completing tasks without stopping.", category: 'motivation' },
  { id: 377, text: "I try not to get distracted.", category: 'motivation' },
  { id: 378, text: "I stay motivated when I see progress.", category: 'motivation' },
  { id: 379, text: "I enjoy hard work that helps me grow.", category: 'motivation' },
  { id: 380, text: "I try to stay determined.", category: 'motivation' },
  { id: 381, text: "I like working toward goals.", category: 'motivation' },
  { id: 382, text: "I enjoy finishing something all by myself.", category: 'motivation' },
  { id: 383, text: "I try to join new activities.", category: 'motivation' },
  { id: 384, text: "I try to stay on track even when bored.", category: 'motivation' },
  { id: 385, text: "I try harder when someone encourages me.", category: 'motivation' },
  { id: 386, text: "I feel proud when I don't quit.", category: 'motivation' },
  { id: 387, text: "I try to practice things I'm not good at.", category: 'motivation' },
  { id: 388, text: "I like learning because it helps me grow.", category: 'motivation' },
  { id: 389, text: "I try to enjoy every lesson.", category: 'motivation' },
  { id: 390, text: "I try for a long time when needed.", category: 'motivation' },
  { id: 391, text: "I don't give up after one mistake.", category: 'motivation' },
  { id: 392, text: "I try to solve problems by myself first.", category: 'motivation' },
  { id: 393, text: "I like learning with friends.", category: 'motivation' },
  { id: 394, text: "I stay motivated when something is fun.", category: 'motivation' },
  { id: 395, text: "I remind myself not to quit.", category: 'motivation' },
  { id: 396, text: "I enjoy trying again until I get it.", category: 'motivation' },
  { id: 397, text: "I feel strong when I complete hard tasks.", category: 'motivation' },
  { id: 398, text: "I keep learning even after school.", category: 'motivation' },
  { id: 399, text: "I try to be proud of my effort.", category: 'motivation' },
  { id: 400, text: "I do my best in everything I try.", category: 'motivation' }
];

// ATTENTION & BEHAVIOUR (100 questions: Q401-Q500)
export const attentionBehaviourQuestions: ApprovedKidsQuestion[] = [
  { id: 401, text: "I pay attention when people talk.", category: 'attention-behaviour' },
  { id: 402, text: "I stay on task.", category: 'attention-behaviour' },
  { id: 403, text: "I sit quietly when needed.", category: 'attention-behaviour' },
  { id: 404, text: "I follow rules.", category: 'attention-behaviour' },
  { id: 405, text: "I slow down when needed.", category: 'attention-behaviour' },
  { id: 406, text: "I try to listen the first time.", category: 'attention-behaviour' },
  { id: 407, text: "I keep my eyes on the speaker.", category: 'attention-behaviour' },
  { id: 408, text: "I wait for instructions before starting.", category: 'attention-behaviour' },
  { id: 409, text: "I try not to interrupt others.", category: 'attention-behaviour' },
  { id: 410, text: "I raise my hand before speaking.", category: 'attention-behaviour' },
  { id: 411, text: "I stay calm during lessons.", category: 'attention-behaviour' },
  { id: 412, text: "I try to stay in my seat when required.", category: 'attention-behaviour' },
  { id: 413, text: "I focus on the work in front of me.", category: 'attention-behaviour' },
  { id: 414, text: "I try not to get distracted easily.", category: 'attention-behaviour' },
  { id: 415, text: "I listen to directions carefully.", category: 'attention-behaviour' },
  { id: 416, text: "I follow class routines.", category: 'attention-behaviour' },
  { id: 417, text: "I stay quiet when others are working.", category: 'attention-behaviour' },
  { id: 418, text: "I use an inside voice when needed.", category: 'attention-behaviour' },
  { id: 419, text: "I try to finish tasks without rushing.", category: 'attention-behaviour' },
  { id: 420, text: "I keep my hands and feet to myself.", category: 'attention-behaviour' },
  { id: 421, text: "I walk safely in the classroom.", category: 'attention-behaviour' },
  { id: 422, text: "I try to keep my area neat.", category: 'attention-behaviour' },
  { id: 423, text: "I listen closely to my teacher.", category: 'attention-behaviour' },
  { id: 424, text: "I think before I speak.", category: 'attention-behaviour' },
  { id: 425, text: "I wait patiently in line.", category: 'attention-behaviour' },
  { id: 426, text: "I stay focused even if others are talking.", category: 'attention-behaviour' },
  { id: 427, text: "I try to control my excitement.", category: 'attention-behaviour' },
  { id: 428, text: "I look at the board when learning.", category: 'attention-behaviour' },
  { id: 429, text: "I try not to fidget too much.", category: 'attention-behaviour' },
  { id: 430, text: "I listen to reminders politely.", category: 'attention-behaviour' },
  { id: 431, text: "I sit properly during lessons.", category: 'attention-behaviour' },
  { id: 432, text: "I stay in the right spot during activities.", category: 'attention-behaviour' },
  { id: 433, text: "I follow the schedule.", category: 'attention-behaviour' },
  { id: 434, text: "I try to remember the rules.", category: 'attention-behaviour' },
  { id: 435, text: "I keep my voice low when needed.", category: 'attention-behaviour' },
  { id: 436, text: "I pay attention to details.", category: 'attention-behaviour' },
  { id: 437, text: "I listen without arguing.", category: 'attention-behaviour' },
  { id: 438, text: "I stay calm when someone annoys me.", category: 'attention-behaviour' },
  { id: 439, text: "I try to finish work before talking to friends.", category: 'attention-behaviour' },
  { id: 440, text: "I follow steps in order.", category: 'attention-behaviour' },
  { id: 441, text: "I try not to talk out of turn.", category: 'attention-behaviour' },
  { id: 442, text: "I look at my work carefully.", category: 'attention-behaviour' },
  { id: 443, text: "I wait for my turn during activities.", category: 'attention-behaviour' },
  { id: 444, text: "I move around only when allowed.", category: 'attention-behaviour' },
  { id: 445, text: "I read instructions before starting.", category: 'attention-behaviour' },
  { id: 446, text: "I listen to safety rules.", category: 'attention-behaviour' },
  { id: 447, text: "I stop what I'm doing when told.", category: 'attention-behaviour' },
  { id: 448, text: "I try to stay organized.", category: 'attention-behaviour' },
  { id: 449, text: "I clean up after myself.", category: 'attention-behaviour' },
  { id: 450, text: "I try not to forget my materials.", category: 'attention-behaviour' },
  { id: 451, text: "I follow the teacher's directions quickly.", category: 'attention-behaviour' },
  { id: 452, text: "I keep my focus during group work.", category: 'attention-behaviour' },
  { id: 453, text: "I listen without complaining.", category: 'attention-behaviour' },
  { id: 454, text: "I try not to rush through work.", category: 'attention-behaviour' },
  { id: 455, text: "I ask questions if I'm confused.", category: 'attention-behaviour' },
  { id: 456, text: "I use time wisely.", category: 'attention-behaviour' },
  { id: 457, text: "I stay calm when something goes wrong.", category: 'attention-behaviour' },
  { id: 458, text: "I stay in control of my body.", category: 'attention-behaviour' },
  { id: 459, text: "I know when to be serious.", category: 'attention-behaviour' },
  { id: 460, text: "I try to stay quiet during tests.", category: 'attention-behaviour' },
  { id: 461, text: "I listen when classmates are speaking.", category: 'attention-behaviour' },
  { id: 462, text: "I behave politely in class.", category: 'attention-behaviour' },
  { id: 463, text: "I keep my mind on learning.", category: 'attention-behaviour' },
  { id: 464, text: "I move quietly around the classroom.", category: 'attention-behaviour' },
  { id: 465, text: "I try to follow instructions the first time.", category: 'attention-behaviour' },
  { id: 466, text: "I respect quiet time.", category: 'attention-behaviour' },
  { id: 467, text: "I do what I'm asked right away.", category: 'attention-behaviour' },
  { id: 468, text: "I try not to disturb others.", category: 'attention-behaviour' },
  { id: 469, text: "I stay calm before answering questions.", category: 'attention-behaviour' },
  { id: 470, text: "I keep track of my belongings.", category: 'attention-behaviour' },
  { id: 471, text: "I try not to argue with rules.", category: 'attention-behaviour' },
  { id: 472, text: "I follow classroom expectations.", category: 'attention-behaviour' },
  { id: 473, text: "I wait until a teacher finishes talking.", category: 'attention-behaviour' },
  { id: 474, text: "I listen even when I don't feel like it.", category: 'attention-behaviour' },
  { id: 475, text: "I try to finish my work neatly.", category: 'attention-behaviour' },
  { id: 476, text: "I keep my desk tidy.", category: 'attention-behaviour' },
  { id: 477, text: "I focus on one task at a time.", category: 'attention-behaviour' },
  { id: 478, text: "I sit still when I need to.", category: 'attention-behaviour' },
  { id: 479, text: "I listen to instructions all the way through.", category: 'attention-behaviour' },
  { id: 480, text: "I stop talking when someone else starts.", category: 'attention-behaviour' },
  { id: 481, text: "I stay quiet in the hallways.", category: 'attention-behaviour' },
  { id: 482, text: "I follow safety rules outside.", category: 'attention-behaviour' },
  { id: 483, text: "I listen to warnings.", category: 'attention-behaviour' },
  { id: 484, text: "I control my body during activities.", category: 'attention-behaviour' },
  { id: 485, text: "I try to stay focused during reading time.", category: 'attention-behaviour' },
  { id: 486, text: "I use materials correctly.", category: 'attention-behaviour' },
  { id: 487, text: "I follow rules even without reminders.", category: 'attention-behaviour' },
  { id: 488, text: "I stay calm when waiting.", category: 'attention-behaviour' },
  { id: 489, text: "I try to do my best behaviour every day.", category: 'attention-behaviour' },
  { id: 490, text: "I respect personal space.", category: 'attention-behaviour' },
  { id: 491, text: "I listen carefully during stories.", category: 'attention-behaviour' },
  { id: 492, text: "I try not to lose my things.", category: 'attention-behaviour' },
  { id: 493, text: "I fix my mistakes calmly.", category: 'attention-behaviour' },
  { id: 494, text: "I sit up straight when learning.", category: 'attention-behaviour' },
  { id: 495, text: "I ask for help quietly.", category: 'attention-behaviour' },
  { id: 496, text: "I follow directions step by step.", category: 'attention-behaviour' },
  { id: 497, text: "I try to stay focused until the end.", category: 'attention-behaviour' },
  { id: 498, text: "I keep my hands to myself in line.", category: 'attention-behaviour' },
  { id: 499, text: "I behave kindly during group time.", category: 'attention-behaviour' },
  { id: 500, text: "I pay attention even when I'm distracted.", category: 'attention-behaviour' }
];

// Combine all questions
export const allApprovedQuestions: ApprovedKidsQuestion[] = [
  ...problemSolvingQuestions,
  ...decisionMakingQuestions,
  ...socialThinkingQuestions,
  ...motivationQuestions,
  ...attentionBehaviourQuestions
];

// Helper function to get questions by category
export const getQuestionsByCategory = (category: ApprovedKidsQuestion['category']) => {
  return allApprovedQuestions.filter(q => q.category === category);
};

// Helper function to calculate results
export interface AssessmentResults {
  'problem-solving': number;
  'decision-making': number;
  'social-thinking': number;
  'motivation': number;
  'attention-behaviour': number;
  totalScore: number;
  questionsAnswered: number;
}

export const calculateResults = (
  answers: Record<number, 1 | 2 | 3> // 1=☹, 2=😐, 3=😊
): AssessmentResults => {
  const scores: AssessmentResults = {
    'problem-solving': 0,
    'decision-making': 0,
    'social-thinking': 0,
    'motivation': 0,
    'attention-behaviour': 0,
    totalScore: 0,
    questionsAnswered: 0
  };

  allApprovedQuestions.forEach(question => {
    const answer = answers[question.id];
    if (answer) {
      scores[question.category] += answer;
      scores.totalScore += answer;
      scores.questionsAnswered += 1;
    }
  });

  return scores;
};

// Get category info
export const CATEGORY_INFO = {
  'problem-solving': {
    emoji: '🧩',
    title: 'Problem-Solving',
    description: 'How you solve puzzles and challenges!',
    color: 'from-purple-500 to-pink-500'
  },
  'decision-making': {
    emoji: '🚦',
    title: 'Decision-Making',
    description: 'How you make good choices!',
    color: 'from-blue-500 to-cyan-500'
  },
  'social-thinking': {
    emoji: '🌈',
    title: 'Social Thinking',
    description: 'How you work and play with others!',
    color: 'from-green-500 to-emerald-500'
  },
  'motivation': {
    emoji: '⭐',
    title: 'Motivation',
    description: 'How you try your best!',
    color: 'from-yellow-500 to-orange-500'
  },
  'attention-behaviour': {
    emoji: '🎯',
    title: 'Attention & Behaviour',
    description: 'How you focus and follow rules!',
    color: 'from-red-500 to-pink-500'
  }
} as const;
