import { Question } from '../types';

/**
 * COMPREHENSIVE TERTIARY STUDENT QUESTION BANK (AGES 15-25)
 * Total: 600 questions across 3 frameworks
 * 
 * Framework 1: Kolb Learning Styles - 200 questions
 * Framework 2: Sternberg Thinking Styles - 200 questions  
 * Framework 3: Dual-Process Decision Making - 200 questions
 * 
 * These questions are designed for:
 * - Tertiary education (university/college students)
 * - Enhanced academic and career guidance
 * - Ghana education system mapping
 * - Professional development pathways
 */

// ============================================================================
// FRAMEWORK 1: KOLB LEARNING STYLES (200 QUESTIONS)
// Four styles: Diverging, Assimilating, Converging, Accommodating
// 50 questions per style = 200 total
// ============================================================================

export const kolbQuestionsTertiary: Question[] = [
  // ===== DIVERGING STYLE (50 QUESTIONS) =====
  // People who learn through observation, imagination, reflection, perspective-taking
  { id: 1, text: "I enjoy learning by watching others before trying something myself", dimension: "CE" },
  { id: 2, text: "I like to look at situations from many different angles", dimension: "RO" },
  { id: 3, text: "I prefer group discussions to hands-on activities", dimension: "RO" },
  { id: 4, text: "I learn best when I can reflect quietly on new ideas", dimension: "RO" },
  { id: 5, text: "I enjoy subjects that allow creativity or storytelling", dimension: "CE" },
  { id: 6, text: "I find it easy to understand how others feel", dimension: "CE" },
  { id: 7, text: "I like activities where multiple answers are possible", dimension: "CE" },
  { id: 8, text: "I need time to think before expressing my ideas", dimension: "RO" },
  { id: 9, text: "I prefer teachers who explain concepts using real-life examples", dimension: "CE" },
  { id: 10, text: "I enjoy brainstorming with others", dimension: "CE" },
  { id: 11, text: "I like to observe details that others often miss", dimension: "RO" },
  { id: 12, text: "I enjoy visual learning materials like diagrams or images", dimension: "CE" },
  { id: 13, text: "I prefer open-ended tasks over structured ones", dimension: "CE" },
  { id: 14, text: "I learn best through examples rather than strict instructions", dimension: "CE" },
  { id: 15, text: "I like imagining 'what if' scenarios", dimension: "CE" },
  { id: 16, text: "I enjoy expressing myself through art, writing, or music", dimension: "CE" },
  { id: 17, text: "I am good at noticing patterns in events or behaviors", dimension: "RO" },
  { id: 18, text: "I prefer watching demonstrations instead of doing activities immediately", dimension: "RO" },
  { id: 19, text: "I enjoy exploring ideas without worrying about solutions yet", dimension: "RO" },
  { id: 20, text: "I think deeply before making a comment in class", dimension: "RO" },
  { id: 21, text: "I enjoy listening to other people's opinions", dimension: "RO" },
  { id: 22, text: "I learn best when the environment is calm", dimension: "RO" },
  { id: 23, text: "I like learning experiences that involve empathy", dimension: "CE" },
  { id: 24, text: "I enjoy reflecting on my daily experiences", dimension: "RO" },
  { id: 25, text: "I find it easier to understand concepts when linked to stories", dimension: "CE" },
  { id: 26, text: "I like learning by comparing different viewpoints", dimension: "RO" },
  { id: 27, text: "I learn well when exposed to different cultures and perspectives", dimension: "CE" },
  { id: 28, text: "I prefer analyzing why something happened rather than how to fix it", dimension: "RO" },
  { id: 29, text: "I value emotional insight in learning situations", dimension: "CE" },
  { id: 30, text: "I enjoy subjects that explore human behavior", dimension: "CE" },
  { id: 31, text: "I prefer to understand the meaning behind things before acting", dimension: "RO" },
  { id: 32, text: "I learn best by watching videos or observing examples", dimension: "RO" },
  { id: 33, text: "I think deeply about past events", dimension: "RO" },
  { id: 34, text: "I enjoy connecting ideas from different subjects", dimension: "RO" },
  { id: 35, text: "I like to take time before making decisions about my work", dimension: "RO" },
  { id: 36, text: "I enjoy reflecting alone after group work", dimension: "RO" },
  { id: 37, text: "I remember information better when it relates to personal experiences", dimension: "CE" },
  { id: 38, text: "I prefer flexible learning environments", dimension: "CE" },
  { id: 39, text: "I enjoy analyzing how people respond to situations", dimension: "RO" },
  { id: 40, text: "I enjoy exploring themes, metaphors, or symbolism", dimension: "CE" },
  { id: 41, text: "I like relating classroom learning to real-life stories", dimension: "CE" },
  { id: 42, text: "I prefer discussions more than tests", dimension: "CE" },
  { id: 43, text: "I enjoy considering many possibilities before choosing one", dimension: "RO" },
  { id: 44, text: "I learn best when ideas are presented visually", dimension: "CE" },
  { id: 45, text: "I enjoy thinking about the emotional impact of events", dimension: "CE" },
  { id: 46, text: "I prefer learning from others' experiences", dimension: "RO" },
  { id: 47, text: "I enjoy reflecting on past mistakes to improve", dimension: "RO" },
  { id: 48, text: "I like asking 'why' something matters", dimension: "RO" },
  { id: 49, text: "I enjoy thinking about future possibilities", dimension: "CE" },
  { id: 50, text: "I learn best when I can observe first and act later", dimension: "RO" },

  // ===== ASSIMILATING STYLE (50 QUESTIONS) =====
  // Logical, conceptual, structured learning; prefers theories and organized information
  { id: 51, text: "I enjoy learning through clear explanations and theories", dimension: "AC" },
  { id: 52, text: "I prefer structured lessons with defined goals", dimension: "AC" },
  { id: 53, text: "I learn best when information is organized logically", dimension: "AC" },
  { id: 54, text: "I like understanding the 'big idea' before focusing on details", dimension: "AC" },
  { id: 55, text: "I enjoy analyzing data and information", dimension: "RO" },
  { id: 56, text: "I prefer facts over opinions", dimension: "AC" },
  { id: 57, text: "I enjoy reading to learn new concepts", dimension: "RO" },
  { id: 58, text: "I prefer instructors who teach in a step-by-step manner", dimension: "AC" },
  { id: 59, text: "I enjoy problem-solving using logic", dimension: "AC" },
  { id: 60, text: "I prefer working alone rather than in groups", dimension: "RO" },
  { id: 61, text: "I like subjects that require careful thinking", dimension: "AC" },
  { id: 62, text: "I enjoy abstract ideas more than practical tasks", dimension: "AC" },
  { id: 63, text: "I prefer textbooks and structured notes", dimension: "AC" },
  { id: 64, text: "I learn best when information is concise and clear", dimension: "AC" },
  { id: 65, text: "I enjoy organizing information into categories", dimension: "AC" },
  { id: 66, text: "I like understanding the principles behind a concept", dimension: "AC" },
  { id: 67, text: "I prefer theories rather than personal stories", dimension: "AC" },
  { id: 68, text: "I enjoy analyzing relationships between ideas", dimension: "AC" },
  { id: 69, text: "I value accuracy in learning", dimension: "AC" },
  { id: 70, text: "I prefer working with charts, graphs, and models", dimension: "AC" },
  { id: 71, text: "I enjoy exploring patterns in information", dimension: "RO" },
  { id: 72, text: "I learn best when I have time to think quietly", dimension: "RO" },
  { id: 73, text: "I enjoy creating outlines or summaries", dimension: "AC" },
  { id: 74, text: "I prefer concepts over hands-on practice", dimension: "AC" },
  { id: 75, text: "I learn better when instructions are explicit", dimension: "AC" },
  { id: 76, text: "I enjoy analyzing why a method works", dimension: "AC" },
  { id: 77, text: "I prefer predictable learning environments", dimension: "AC" },
  { id: 78, text: "I like understanding rules and systems", dimension: "AC" },
  { id: 79, text: "I learn best when I can break information into steps", dimension: "AC" },
  { id: 80, text: "I enjoy mathematical or analytical tasks", dimension: "AC" },
  { id: 81, text: "I prefer theoretical discussions", dimension: "AC" },
  { id: 82, text: "I enjoy connecting facts to create new ideas", dimension: "AC" },
  { id: 83, text: "I prefer reading instructions before trying something", dimension: "RO" },
  { id: 84, text: "I enjoy reviewing academic articles or reports", dimension: "AC" },
  { id: 85, text: "I favor accuracy over speed in learning", dimension: "AC" },
  { id: 86, text: "I like solving problems using established methods", dimension: "AC" },
  { id: 87, text: "I prefer lectures to hands-on labs", dimension: "AC" },
  { id: 88, text: "I enjoy learning through definitions and formulas", dimension: "AC" },
  { id: 89, text: "I learn best when information is presented logically", dimension: "AC" },
  { id: 90, text: "I prefer objective feedback", dimension: "AC" },
  { id: 91, text: "I enjoy building logical arguments", dimension: "AC" },
  { id: 92, text: "I like learning tools that provide structure", dimension: "AC" },
  { id: 93, text: "I enjoy interpreting diagrams and conceptual maps", dimension: "AC" },
  { id: 94, text: "I prefer quiet environments for learning", dimension: "RO" },
  { id: 95, text: "I enjoy exploring theoretical possibilities", dimension: "AC" },
  { id: 96, text: "I prefer long, detailed explanations", dimension: "AC" },
  { id: 97, text: "I value factual evidence in learning", dimension: "AC" },
  { id: 98, text: "I like to understand models before using them", dimension: "AC" },
  { id: 99, text: "I learn best when concepts are categorized clearly", dimension: "AC" },
  { id: 100, text: "I prefer intellectual challenges over practical tasks", dimension: "AC" },

  // ===== CONVERGING STYLE (50 QUESTIONS) =====
  // Applies ideas in practical, technical, problem-solving ways
  { id: 101, text: "I learn best by applying ideas to real problems", dimension: "AE" },
  { id: 102, text: "I enjoy experimenting with solutions", dimension: "AE" },
  { id: 103, text: "I prefer technical tasks over open discussions", dimension: "AC" },
  { id: 104, text: "I enjoy learning new tools or technologies", dimension: "AE" },
  { id: 105, text: "I like working toward concrete results", dimension: "AE" },
  { id: 106, text: "I prefer clear answers instead of many possibilities", dimension: "AC" },
  { id: 107, text: "I enjoy building things or creating prototypes", dimension: "AE" },
  { id: 108, text: "I learn best through trial and error", dimension: "AE" },
  { id: 109, text: "I like solving practical problems", dimension: "AE" },
  { id: 110, text: "I prefer structured activities with specific outcomes", dimension: "AC" },
  { id: 111, text: "I enjoy figuring out how things work", dimension: "AC" },
  { id: 112, text: "I enjoy tasks requiring analytical problem-solving", dimension: "AC" },
  { id: 113, text: "I like applying theories to real-life situations", dimension: "AE" },
  { id: 114, text: "I prefer clear, measurable goals in learning", dimension: "AC" },
  { id: 115, text: "I enjoy technical subjects like maths or science", dimension: "AC" },
  { id: 116, text: "I like fixing things or improving systems", dimension: "AE" },
  { id: 117, text: "I learn best when I can test my ideas", dimension: "AE" },
  { id: 118, text: "I prefer working independently on tasks", dimension: "AC" },
  { id: 119, text: "I like learning through doing rather than talking", dimension: "AE" },
  { id: 120, text: "I prefer efficiency over long discussions", dimension: "AC" },
  { id: 121, text: "I enjoy practical assignments", dimension: "AE" },
  { id: 122, text: "I like learning skills that are directly useful", dimension: "AE" },
  { id: 123, text: "I enjoy being challenged by technical problems", dimension: "AC" },
  { id: 124, text: "I prefer tasks with one correct method", dimension: "AC" },
  { id: 125, text: "I like using logic to solve practical issues", dimension: "AC" },
  { id: 126, text: "I learn best through experiments", dimension: "AE" },
  { id: 127, text: "I enjoy step-by-step tasks that lead to results", dimension: "AC" },
  { id: 128, text: "I prefer action-oriented learning", dimension: "AE" },
  { id: 129, text: "I like applying classroom knowledge to real tasks", dimension: "AE" },
  { id: 130, text: "I prefer measurable progress", dimension: "AC" },
  { id: 131, text: "I enjoy using formulas or procedures", dimension: "AC" },
  { id: 132, text: "I like learning by trying new strategies", dimension: "AE" },
  { id: 133, text: "I prefer direct feedback", dimension: "AE" },
  { id: 134, text: "I enjoy tasks that require precision", dimension: "AC" },
  { id: 135, text: "I learn best through hands-on experiments", dimension: "AE" },
  { id: 136, text: "I like learning through problem-solving games", dimension: "AE" },
  { id: 137, text: "I prefer to see results quickly", dimension: "AE" },
  { id: 138, text: "I enjoy comparing solutions to find the best one", dimension: "AC" },
  { id: 139, text: "I prefer practical demonstrations", dimension: "AE" },
  { id: 140, text: "I enjoy testing whether ideas work in practice", dimension: "AE" },
  { id: 141, text: "I like learning when there is a clear purpose", dimension: "AC" },
  { id: 142, text: "I learn best when goals are clearly stated", dimension: "AC" },
  { id: 143, text: "I enjoy applying new skills immediately", dimension: "AE" },
  { id: 144, text: "I prefer active learning", dimension: "AE" },
  { id: 145, text: "I enjoy learning through simulations", dimension: "AE" },
  { id: 146, text: "I learn best when I can manipulate or change something", dimension: "AE" },
  { id: 147, text: "I enjoy figuring out efficient solutions", dimension: "AC" },
  { id: 148, text: "I prefer practical tasks over abstract discussions", dimension: "AE" },
  { id: 149, text: "I like using tools or equipment in learning", dimension: "AE" },
  { id: 150, text: "I learn best when outcomes are measurable", dimension: "AC" },

  // ===== ACCOMMODATING STYLE (50 QUESTIONS) =====
  // Hands-on, experimental, intuitive, risk-taking, adaptive
  { id: 151, text: "I enjoy learning through hands-on activities", dimension: "AE" },
  { id: 152, text: "I like trying new experiences to learn", dimension: "CE" },
  { id: 153, text: "I prefer flexible learning environments", dimension: "CE" },
  { id: 154, text: "I enjoy learning by doing rather than thinking first", dimension: "AE" },
  { id: 155, text: "I like taking risks in learning", dimension: "CE" },
  { id: 156, text: "I learn best when I can follow my intuition", dimension: "CE" },
  { id: 157, text: "I prefer tasks that allow freedom and exploration", dimension: "CE" },
  { id: 158, text: "I enjoy group work and teamwork", dimension: "CE" },
  { id: 159, text: "I like learning from real experiences", dimension: "CE" },
  { id: 160, text: "I enjoy adapting to new challenges", dimension: "AE" },
  { id: 161, text: "I prefer active participation over observation", dimension: "AE" },
  { id: 162, text: "I like figuring things out on the spot", dimension: "AE" },
  { id: 163, text: "I learn best when I can make quick decisions", dimension: "AE" },
  { id: 164, text: "I prefer open-ended projects", dimension: "CE" },
  { id: 165, text: "I enjoy moving around during learning", dimension: "AE" },
  { id: 166, text: "I like exploring new ideas through experimentation", dimension: "AE" },
  { id: 167, text: "I prefer spontaneous learning activities", dimension: "CE" },
  { id: 168, text: "I enjoy discovering solutions without instructions", dimension: "AE" },
  { id: 169, text: "I like learning by taking action immediately", dimension: "AE" },
  { id: 170, text: "I enjoy solving problems creatively", dimension: "CE" },
  { id: 171, text: "I prefer flexible deadlines", dimension: "CE" },
  { id: 172, text: "I enjoy testing ideas through trial and error", dimension: "AE" },
  { id: 173, text: "I like learning through adventure", dimension: "CE" },
  { id: 174, text: "I enjoy leadership opportunities in groups", dimension: "AE" },
  { id: 175, text: "I prefer doing something rather than analyzing it", dimension: "AE" },
  { id: 176, text: "I like learning through mistakes", dimension: "CE" },
  { id: 177, text: "I learn best in fast-paced environments", dimension: "AE" },
  { id: 178, text: "I prefer learning activities that involve movement", dimension: "AE" },
  { id: 179, text: "I enjoy tasks that allow improvisation", dimension: "CE" },
  { id: 180, text: "I prefer exploring solutions independently", dimension: "AE" },
  { id: 181, text: "I like adapting quickly to changes", dimension: "AE" },
  { id: 182, text: "I enjoy experimenting with different approaches", dimension: "AE" },
  { id: 183, text: "I prefer minimal structure in learning", dimension: "CE" },
  { id: 184, text: "I like figuring out solutions through action", dimension: "AE" },
  { id: 185, text: "I enjoy learning when the environment is energetic", dimension: "CE" },
  { id: 186, text: "I learn best when I have freedom to explore", dimension: "CE" },
  { id: 187, text: "I prefer direct experience over theory", dimension: "CE" },
  { id: 188, text: "I enjoy activities requiring creativity and spontaneity", dimension: "CE" },
  { id: 189, text: "I learn well in group projects", dimension: "CE" },
  { id: 190, text: "I like discovering things myself rather than being told", dimension: "AE" },
  { id: 191, text: "I enjoy switching between different tasks", dimension: "CE" },
  { id: 192, text: "I learn best through hands-on tasks", dimension: "AE" },
  { id: 193, text: "I prefer quick feedback", dimension: "AE" },
  { id: 194, text: "I enjoy experimenting with tools and materials", dimension: "AE" },
  { id: 195, text: "I prefer learning by jumping into the task", dimension: "AE" },
  { id: 196, text: "I enjoy unstructured challenges", dimension: "CE" },
  { id: 197, text: "I like experimenting without detailed instructions", dimension: "AE" },
  { id: 198, text: "I learn well in dynamic environments", dimension: "CE" },
  { id: 199, text: "I enjoy learning through personal experiences", dimension: "CE" },
  { id: 200, text: "I like exploring unfamiliar tasks with enthusiasm", dimension: "CE" },
];

// ============================================================================
// FRAMEWORK 2: STERNBERG THINKING STYLES (200 QUESTIONS)
// Three styles: Analytical, Creative, Practical
// ~66-67 questions per style = 200 total
// ============================================================================

export const sternbergQuestionsTertiary: Question[] = [
  // ===== ANALYTICAL THINKING STYLE (~66 QUESTIONS) =====
  // Evaluate, compare, break down problems, examine logic, analyze details
  { id: 1, text: "I enjoy breaking problems into smaller parts to understand them", dimension: "analytical" },
  { id: 2, text: "I like evaluating different arguments before choosing one", dimension: "analytical" },
  { id: 3, text: "I prefer tasks that require logical thinking", dimension: "analytical" },
  { id: 4, text: "I enjoy identifying mistakes in reasoning", dimension: "analytical" },
  { id: 5, text: "I like comparing different solutions to see which is best", dimension: "analytical" },
  { id: 6, text: "I enjoy subjects that require analysis, such as math or science", dimension: "analytical" },
  { id: 7, text: "I like organizing information into categories", dimension: "analytical" },
  { id: 8, text: "I enjoy examining the causes behind events", dimension: "analytical" },
  { id: 9, text: "I prefer step-by-step instructions", dimension: "analytical" },
  { id: 10, text: "I enjoy solving puzzles that require logic", dimension: "analytical" },
  { id: 11, text: "I like tasks that challenge my reasoning ability", dimension: "analytical" },
  { id: 12, text: "I enjoy analyzing data to find patterns", dimension: "analytical" },
  { id: 13, text: "I prefer structured tasks over open-ended ones", dimension: "analytical" },
  { id: 14, text: "I like evaluating the strengths and weaknesses of ideas", dimension: "analytical" },
  { id: 15, text: "I enjoy identifying the main point in discussions", dimension: "analytical" },
  { id: 16, text: "I like organizing my thoughts before speaking", dimension: "analytical" },
  { id: 17, text: "I enjoy comparing different viewpoints", dimension: "analytical" },
  { id: 18, text: "I prefer checking facts before accepting them", dimension: "analytical" },
  { id: 19, text: "I enjoy tasks that require accuracy and precision", dimension: "analytical" },
  { id: 20, text: "I like identifying what's wrong in arguments or statements", dimension: "analytical" },
  { id: 21, text: "I prefer assignments that involve research and analysis", dimension: "analytical" },
  { id: 22, text: "I enjoy solving academic problems that require logic", dimension: "analytical" },
  { id: 23, text: "I like evaluating whether information is reliable", dimension: "analytical" },
  { id: 24, text: "I prefer detailed explanations", dimension: "analytical" },
  { id: 25, text: "I enjoy identifying contradictions in information", dimension: "analytical" },
  { id: 26, text: "I like thinking through decisions carefully", dimension: "analytical" },
  { id: 27, text: "I enjoy examining the pros and cons of choices", dimension: "analytical" },
  { id: 28, text: "I prefer evaluating evidence before reaching conclusions", dimension: "analytical" },
  { id: 29, text: "I enjoy making well-informed decisions", dimension: "analytical" },
  { id: 30, text: "I like comparing different methods to solve a problem", dimension: "analytical" },
  { id: 31, text: "I enjoy analyzing why something did or didn't work", dimension: "analytical" },
  { id: 32, text: "I prefer work that requires careful thought", dimension: "analytical" },
  { id: 33, text: "I enjoy looking for hidden patterns", dimension: "analytical" },
  { id: 34, text: "I like asking questions that clarify information", dimension: "analytical" },
  { id: 35, text: "I prefer solving tasks that require deep thinking", dimension: "analytical" },
  { id: 36, text: "I enjoy applying logic to understand issues", dimension: "analytical" },
  { id: 37, text: "I like reviewing my work to check for mistakes", dimension: "analytical" },
  { id: 38, text: "I enjoy assignments that require critical thinking", dimension: "analytical" },
  { id: 39, text: "I prefer thinking carefully before reacting", dimension: "analytical" },
  { id: 40, text: "I enjoy making sense of complex ideas", dimension: "analytical" },
  { id: 41, text: "I like identifying the structure behind problems", dimension: "analytical" },
  { id: 42, text: "I enjoy activities that involve comparing options", dimension: "analytical" },
  { id: 43, text: "I prefer tasks that require evaluating details", dimension: "analytical" },
  { id: 44, text: "I enjoy determining the cause of a problem", dimension: "analytical" },
  { id: 45, text: "I like reviewing information to identify flaws", dimension: "analytical" },
  { id: 46, text: "I enjoy breaking down complex texts", dimension: "analytical" },
  { id: 47, text: "I prefer precise instructions in schoolwork", dimension: "analytical" },
  { id: 48, text: "I enjoy checking if information is logically consistent", dimension: "analytical" },
  { id: 49, text: "I like using diagrams to understand ideas", dimension: "analytical" },
  { id: 50, text: "I enjoy organizing information logically", dimension: "analytical" },
  { id: 51, text: "I prefer solving problems that involve rules", dimension: "analytical" },
  { id: 52, text: "I enjoy studying how systems work", dimension: "analytical" },
  { id: 53, text: "I like ensuring my work is logically correct", dimension: "analytical" },
  { id: 54, text: "I enjoy reasoning through academic tasks", dimension: "analytical" },
  { id: 55, text: "I prefer thinking with evidence, not assumptions", dimension: "analytical" },
  { id: 56, text: "I enjoy detecting errors in written text", dimension: "analytical" },
  { id: 57, text: "I like analyzing different causes of a situation", dimension: "analytical" },
  { id: 58, text: "I enjoy evaluating performance using criteria", dimension: "analytical" },
  { id: 59, text: "I prefer assignments where accuracy matters", dimension: "analytical" },
  { id: 60, text: "I enjoy learning new problem-solving methods", dimension: "analytical" },
  { id: 61, text: "I like identifying what makes an argument strong or weak", dimension: "analytical" },
  { id: 62, text: "I enjoy thinking deeply about decisions before acting", dimension: "analytical" },
  { id: 63, text: "I prefer rational explanations over emotional ones", dimension: "analytical" },
  { id: 64, text: "I enjoy tasks that involve comparing data sets", dimension: "analytical" },
  { id: 65, text: "I like identifying gaps in information", dimension: "analytical" },
  { id: 66, text: "I enjoy analyzing what could go wrong before starting a task", dimension: "analytical" },

  // ===== CREATIVE THINKING STYLE (~66 QUESTIONS) =====
  // Imagine, invent, brainstorm, innovate, create original ideas
  { id: 67, text: "I enjoy coming up with new ideas", dimension: "creative" },
  { id: 68, text: "I like imagining different ways to solve a problem", dimension: "creative" },
  { id: 69, text: "I enjoy thinking of creative alternatives", dimension: "creative" },
  { id: 70, text: "I prefer assignments that allow creativity", dimension: "creative" },
  { id: 71, text: "I like linking unrelated ideas together", dimension: "creative" },
  { id: 72, text: "I enjoy exploring 'what if' scenarios", dimension: "creative" },
  { id: 73, text: "I like designing things or creating concepts", dimension: "creative" },
  { id: 74, text: "I enjoy tasks that allow freedom to experiment", dimension: "creative" },
  { id: 75, text: "I prefer open-ended tasks", dimension: "creative" },
  { id: 76, text: "I enjoy expressing myself creatively", dimension: "creative" },
  { id: 77, text: "I like looking for new approaches to old problems", dimension: "creative" },
  { id: 78, text: "I enjoy thinking outside the box", dimension: "creative" },
  { id: 79, text: "I prefer flexible tasks that allow innovation", dimension: "creative" },
  { id: 80, text: "I enjoy imagining future possibilities", dimension: "creative" },
  { id: 81, text: "I like suggesting new ways of doing things", dimension: "creative" },
  { id: 82, text: "I enjoy stories, art, or creative writing", dimension: "creative" },
  { id: 83, text: "I prefer brainstorming before planning", dimension: "creative" },
  { id: 84, text: "I enjoy exploring ideas without restrictions", dimension: "creative" },
  { id: 85, text: "I like thinking about unusual possibilities", dimension: "creative" },
  { id: 86, text: "I enjoy inventing new solutions", dimension: "creative" },
  { id: 87, text: "I prefer making unique contributions to projects", dimension: "creative" },
  { id: 88, text: "I enjoy turning my ideas into real projects", dimension: "creative" },
  { id: 89, text: "I like experimenting with different methods", dimension: "creative" },
  { id: 90, text: "I enjoy rethinking how things are normally done", dimension: "creative" },
  { id: 91, text: "I like coming up with creative answers", dimension: "creative" },
  { id: 92, text: "I enjoy transforming ideas into something meaningful", dimension: "creative" },
  { id: 93, text: "I prefer tasks that let me explore imagination", dimension: "creative" },
  { id: 94, text: "I enjoy finding surprising combinations of ideas", dimension: "creative" },
  { id: 95, text: "I like generating many ideas before choosing one", dimension: "creative" },
  { id: 96, text: "I enjoy asking unusual questions", dimension: "creative" },
  { id: 97, text: "I prefer learning through exploration", dimension: "creative" },
  { id: 98, text: "I enjoy discovering new concepts on my own", dimension: "creative" },
  { id: 99, text: "I like making improvements to existing ideas", dimension: "creative" },
  { id: 100, text: "I enjoy projects that let me innovate", dimension: "creative" },
  { id: 101, text: "I prefer thinking freely without rules", dimension: "creative" },
  { id: 102, text: "I enjoy creating original concepts", dimension: "creative" },
  { id: 103, text: "I like experimenting with creative strategies", dimension: "creative" },
  { id: 104, text: "I enjoy imagining how things could be different", dimension: "creative" },
  { id: 105, text: "I prefer artistic or imaginative work", dimension: "creative" },
  { id: 106, text: "I enjoy designing new ways to present information", dimension: "creative" },
  { id: 107, text: "I like using creativity to solve academic tasks", dimension: "creative" },
  { id: 108, text: "I enjoy thinking about possibilities others may overlook", dimension: "creative" },
  { id: 109, text: "I prefer spontaneous ideas over planned ones", dimension: "creative" },
  { id: 110, text: "I enjoy exploring problems with no clear answers", dimension: "creative" },
  { id: 111, text: "I like viewing problems from unusual angles", dimension: "creative" },
  { id: 112, text: "I enjoy inventing new systems or themes", dimension: "creative" },
  { id: 113, text: "I prefer flexible learning environments", dimension: "creative" },
  { id: 114, text: "I enjoy connecting abstract ideas to create something new", dimension: "creative" },
  { id: 115, text: "I like expressing ideas through visuals or art", dimension: "creative" },
  { id: 116, text: "I enjoy thinking through metaphors", dimension: "creative" },
  { id: 117, text: "I prefer tasks with space for imagination", dimension: "creative" },
  { id: 118, text: "I enjoy mixing ideas from different fields", dimension: "creative" },
  { id: 119, text: "I like turning creative thoughts into action", dimension: "creative" },
  { id: 120, text: "I enjoy discovering patterns in a playful way", dimension: "creative" },
  { id: 121, text: "I prefer colorful, inspiring learning environments", dimension: "creative" },
  { id: 122, text: "I enjoy making unusual connections between concepts", dimension: "creative" },
  { id: 123, text: "I like trying new approaches even if they may fail", dimension: "creative" },
  { id: 124, text: "I enjoy imagining new possibilities for the future", dimension: "creative" },
  { id: 125, text: "I prefer projects that encourage originality", dimension: "creative" },
  { id: 126, text: "I enjoy thinking freely before narrowing ideas", dimension: "creative" },
  { id: 127, text: "I like solving problems creatively rather than logically", dimension: "creative" },
  { id: 128, text: "I enjoy imagining big ideas and possibilities", dimension: "creative" },
  { id: 129, text: "I prefer creative risks over predictable solutions", dimension: "creative" },
  { id: 130, text: "I enjoy creating something unique from scratch", dimension: "creative" },
  { id: 131, text: "I like projects where creativity is more important than rules", dimension: "creative" },
  { id: 132, text: "I enjoy expressing my inner thoughts through creative work", dimension: "creative" },

  // ===== PRACTICAL THINKING STYLE (~68 QUESTIONS) =====
  // Apply knowledge, make real-world decisions, adapt, solve everyday problems
  { id: 133, text: "I enjoy applying what I learn to real-life situations", dimension: "practical" },
  { id: 134, text: "I prefer tasks that have practical value", dimension: "practical" },
  { id: 135, text: "I like solving everyday problems", dimension: "practical" },
  { id: 136, text: "I enjoy figuring out how to make things work", dimension: "practical" },
  { id: 137, text: "I prefer doing tasks rather than discussing them", dimension: "practical" },
  { id: 138, text: "I enjoy making decisions that lead to clear results", dimension: "practical" },
  { id: 139, text: "I like using my skills to complete practical tasks", dimension: "practical" },
  { id: 140, text: "I enjoy improving things to be more efficient", dimension: "practical" },
  { id: 141, text: "I prefer step-by-step actions that produce outcomes", dimension: "practical" },
  { id: 142, text: "I enjoy managing tasks or responsibilities", dimension: "practical" },
  { id: 143, text: "I like solving problems using past experience", dimension: "practical" },
  { id: 144, text: "I enjoy organizing activities for groups", dimension: "practical" },
  { id: 145, text: "I like tasks that require hands-on work", dimension: "practical" },
  { id: 146, text: "I enjoy learning skills that I can use immediately", dimension: "practical" },
  { id: 147, text: "I prefer clear instructions to follow", dimension: "practical" },
  { id: 148, text: "I enjoy working on tasks that have a direct impact", dimension: "practical" },
  { id: 149, text: "I like choosing the fastest way to get results", dimension: "practical" },
  { id: 150, text: "I enjoy making decisions quickly when needed", dimension: "practical" },
  { id: 151, text: "I prefer problem-solving that leads to action", dimension: "practical" },
  { id: 152, text: "I enjoy figuring out how to fix problems", dimension: "practical" },
  { id: 153, text: "I prefer practical solutions over theoretical ones", dimension: "practical" },
  { id: 154, text: "I enjoy planning daily activities effectively", dimension: "practical" },
  { id: 155, text: "I like improving methods to get tasks done faster", dimension: "practical" },
  { id: 156, text: "I enjoy applying theory to real-world challenges", dimension: "practical" },
  { id: 157, text: "I prefer clear goals and outcomes", dimension: "practical" },
  { id: 158, text: "I enjoy working on group tasks with clear roles", dimension: "practical" },
  { id: 159, text: "I like learning skills that help me manage situations", dimension: "practical" },
  { id: 160, text: "I enjoy testing solutions in real settings", dimension: "practical" },
  { id: 161, text: "I prefer straightforward explanations", dimension: "practical" },
  { id: 162, text: "I enjoy adjusting quickly when challenges arise", dimension: "practical" },
  { id: 163, text: "I like making things more efficient", dimension: "practical" },
  { id: 164, text: "I enjoy solving problems that affect daily life", dimension: "practical" },
  { id: 165, text: "I prefer tasks with immediate feedback", dimension: "practical" },
  { id: 166, text: "I enjoy learning things I can use instantly", dimension: "practical" },
  { id: 167, text: "I prefer practical projects over academic essays", dimension: "practical" },
  { id: 168, text: "I enjoy finding ways to make tasks easier", dimension: "practical" },
  { id: 169, text: "I like organizing resources to achieve results", dimension: "practical" },
  { id: 170, text: "I enjoy helping others solve practical issues", dimension: "practical" },
  { id: 171, text: "I prefer real-world examples over theoretical ones", dimension: "practical" },
  { id: 172, text: "I enjoy learning through doing", dimension: "practical" },
  { id: 173, text: "I prefer simple, clear instructions", dimension: "practical" },
  { id: 174, text: "I enjoy improving my environment through action", dimension: "practical" },
  { id: 175, text: "I like evaluating whether something works in practice", dimension: "practical" },
  { id: 176, text: "I enjoy using tools or systems to complete tasks", dimension: "practical" },
  { id: 177, text: "I prefer predictable, structured tasks", dimension: "practical" },
  { id: 178, text: "I enjoy seeing immediate results of my effort", dimension: "practical" },
  { id: 179, text: "I like solving problems quickly", dimension: "practical" },
  { id: 180, text: "I enjoy using practical judgment in difficult situations", dimension: "practical" },
  { id: 181, text: "I prefer tasks where my decisions affect outcomes", dimension: "practical" },
  { id: 182, text: "I enjoy being responsible for results", dimension: "practical" },
  { id: 183, text: "I like adapting solutions to fit real conditions", dimension: "practical" },
  { id: 184, text: "I enjoy finding efficient paths to solutions", dimension: "practical" },
  { id: 185, text: "I like testing whether ideas actually work", dimension: "practical" },
  { id: 186, text: "I enjoy making practical improvements to processes", dimension: "practical" },
  { id: 187, text: "I prefer real-world learning activities", dimension: "practical" },
  { id: 188, text: "I enjoy taking action to solve issues rather than thinking too long", dimension: "practical" },
  { id: 189, text: "I like working with clear task expectations", dimension: "practical" },
  { id: 190, text: "I enjoy troubleshooting problems", dimension: "practical" },
  { id: 191, text: "I prefer learning through hands-on tasks", dimension: "practical" },
  { id: 192, text: "I enjoy choosing methods that save time or energy", dimension: "practical" },
  { id: 193, text: "I like applying feedback immediately", dimension: "practical" },
  { id: 194, text: "I enjoy decision-making based on real needs", dimension: "practical" },
  { id: 195, text: "I prefer functional tasks over creative ones", dimension: "practical" },
  { id: 196, text: "I enjoy adjusting plans to fit real circumstances", dimension: "practical" },
  { id: 197, text: "I prefer working with systems that are efficient", dimension: "practical" },
  { id: 198, text: "I enjoy learning skills that help in daily life", dimension: "practical" },
  { id: 199, text: "I prefer real-world problem solving over theory", dimension: "practical" },
  { id: 200, text: "I enjoy practical success more than academic analysis", dimension: "practical" },
];

// ============================================================================
// FRAMEWORK 3: DUAL-PROCESS DECISION MAKING (200 QUESTIONS)
// Two systems: System 1 (Intuitive), System 2 (Reflective)
// 100 questions per system = 200 total
// ============================================================================

export const dualProcessQuestionsTertiary: Question[] = [
  // ===== SYSTEM 1 – INTUITIVE DECISION STYLE (100 QUESTIONS) =====
  // Fast, automatic, emotion-driven, instinctive, rapid judgments
  { id: 1, text: "I often rely on my first impression when making decisions", dimension: "system1" },
  { id: 2, text: "I can usually sense the right choice without much thought", dimension: "system1" },
  { id: 3, text: "I trust my gut feelings in tough situations", dimension: "system1" },
  { id: 4, text: "I make decisions quickly without needing lots of information", dimension: "system1" },
  { id: 5, text: "I often go with what feels right in the moment", dimension: "system1" },
  { id: 6, text: "I rely on instinct when there isn't time to think", dimension: "system1" },
  { id: 7, text: "I feel confident making spontaneous decisions", dimension: "system1" },
  { id: 8, text: "I like making choices based on how I feel", dimension: "system1" },
  { id: 9, text: "I can understand situations quickly without analyzing them", dimension: "system1" },
  { id: 10, text: "I prefer quick decisions over long discussions", dimension: "system1" },
  { id: 11, text: "I often know the answer before fully thinking it through", dimension: "system1" },
  { id: 12, text: "I am comfortable taking action immediately", dimension: "system1" },
  { id: 13, text: "I can tell when something is wrong almost instantly", dimension: "system1" },
  { id: 14, text: "I decide fast when under pressure", dimension: "system1" },
  { id: 15, text: "I listen to my intuition when choices are unclear", dimension: "system1" },
  { id: 16, text: "I make snap judgments about situations", dimension: "system1" },
  { id: 17, text: "I often recognize patterns without needing to explain them", dimension: "system1" },
  { id: 18, text: "I like following my instincts rather than rules", dimension: "system1" },
  { id: 19, text: "I react quickly when opportunities come", dimension: "system1" },
  { id: 20, text: "I trust my emotional reactions", dimension: "system1" },
  { id: 21, text: "I rely on experience-based feelings rather than logic", dimension: "system1" },
  { id: 22, text: "I make choices even when information is incomplete", dimension: "system1" },
  { id: 23, text: "I can sense danger or problems before they become clear", dimension: "system1" },
  { id: 24, text: "I often choose based on a strong inner feeling", dimension: "system1" },
  { id: 25, text: "I rarely regret my instinctive decisions", dimension: "system1" },
  { id: 26, text: "I make decisions based on what feels natural to me", dimension: "system1" },
  { id: 27, text: "I react quickly when something feels urgent", dimension: "system1" },
  { id: 28, text: "I can guess outcomes fairly accurately", dimension: "system1" },
  { id: 29, text: "I enjoy making decisions fast", dimension: "system1" },
  { id: 30, text: "I don't hesitate much when choosing", dimension: "system1" },
  { id: 31, text: "I follow my instincts about people", dimension: "system1" },
  { id: 32, text: "I prefer acting first and thinking later", dimension: "system1" },
  { id: 33, text: "I go with the option that immediately feels right", dimension: "system1" },
  { id: 34, text: "I understand situations almost instantly", dimension: "system1" },
  { id: 35, text: "I prefer choices that feel comfortable emotionally", dimension: "system1" },
  { id: 36, text: "I trust my first reaction to new information", dimension: "system1" },
  { id: 37, text: "I act quickly when I feel strongly about something", dimension: "system1" },
  { id: 38, text: "I like making decisions without overthinking", dimension: "system1" },
  { id: 39, text: "I can sense when someone is being dishonest", dimension: "system1" },
  { id: 40, text: "I follow my heart in difficult decisions", dimension: "system1" },
  { id: 41, text: "I enjoy the excitement of fast decision-making", dimension: "system1" },
  { id: 42, text: "I often choose based on mood", dimension: "system1" },
  { id: 43, text: "I get a strong sense of what is right or wrong immediately", dimension: "system1" },
  { id: 44, text: "I prefer spontaneous problem-solving", dimension: "system1" },
  { id: 45, text: "I make choices even when I'm not fully sure", dimension: "system1" },
  { id: 46, text: "I enjoy deciding based on instinct during challenges", dimension: "system1" },
  { id: 47, text: "I react quickly when plans change suddenly", dimension: "system1" },
  { id: 48, text: "I follow feelings more than rules", dimension: "system1" },
  { id: 49, text: "I sense when someone needs help without being told", dimension: "system1" },
  { id: 50, text: "I rely on hunches in unfamiliar situations", dimension: "system1" },
  { id: 51, text: "I decide quickly in social situations", dimension: "system1" },
  { id: 52, text: "I often intuitively understand how others feel", dimension: "system1" },
  { id: 53, text: "I feel uncomfortable when decisions take too long", dimension: "system1" },
  { id: 54, text: "I trust my intuition more than other people's advice", dimension: "system1" },
  { id: 55, text: "I like making immediate choices rather than planning", dimension: "system1" },
  { id: 56, text: "I follow impulses confidently", dimension: "system1" },
  { id: 57, text: "I decide based on emotional signals", dimension: "system1" },
  { id: 58, text: "I prefer relying on my senses over deep thinking", dimension: "system1" },
  { id: 59, text: "I am good at making fast judgments", dimension: "system1" },
  { id: 60, text: "I often know the right decision before thinking it through", dimension: "system1" },
  { id: 61, text: "I solve problems quickly without analyzing details", dimension: "system1" },
  { id: 62, text: "I choose based on what seems obvious at the moment", dimension: "system1" },
  { id: 63, text: "I enjoy the ability to think on my feet", dimension: "system1" },
  { id: 64, text: "I feel confident choosing quickly even with risk", dimension: "system1" },
  { id: 65, text: "I react fast when opportunities arise", dimension: "system1" },
  { id: 66, text: "I rely on internal signals when confused", dimension: "system1" },
  { id: 67, text: "I know when something feels 'off' immediately", dimension: "system1" },
  { id: 68, text: "I prefer relying on my instincts in unfamiliar environments", dimension: "system1" },
  { id: 69, text: "I quickly sense if a plan will work", dimension: "system1" },
  { id: 70, text: "I feel emotionally drawn to certain choices", dimension: "system1" },
  { id: 71, text: "I prefer experimenting quickly rather than planning", dimension: "system1" },
  { id: 72, text: "I use intuition to navigate social interactions", dimension: "system1" },
  { id: 73, text: "I make choices without needing full clarity", dimension: "system1" },
  { id: 74, text: "I often act before thinking deeply", dimension: "system1" },
  { id: 75, text: "I enjoy trusting my impulses", dimension: "system1" },
  { id: 76, text: "I decide based on emotional comfort", dimension: "system1" },
  { id: 77, text: "I feel confident in snap decisions", dimension: "system1" },
  { id: 78, text: "I can interpret social cues instantly", dimension: "system1" },
  { id: 79, text: "I follow what feels meaningful in the moment", dimension: "system1" },
  { id: 80, text: "I choose based on instinct when logic is unclear", dimension: "system1" },
  { id: 81, text: "I notice emotional shifts quickly", dimension: "system1" },
  { id: 82, text: "I often sense the right answer immediately", dimension: "system1" },
  { id: 83, text: "I prefer instinctive solutions to complicated analysis", dimension: "system1" },
  { id: 84, text: "I react fast to unexpected changes", dimension: "system1" },
  { id: 85, text: "I sense opportunities before others do", dimension: "system1" },
  { id: 86, text: "I rely on feelings to evaluate choices", dimension: "system1" },
  { id: 87, text: "I prefer making choices quickly rather than gathering information", dimension: "system1" },
  { id: 88, text: "I use intuition to solve daily problems", dimension: "system1" },
  { id: 89, text: "I can detect when something is wrong with little evidence", dimension: "system1" },
  { id: 90, text: "I trust my feelings about people I meet", dimension: "system1" },
  { id: 91, text: "I prefer fast-paced decision situations", dimension: "system1" },
  { id: 92, text: "I enjoy intuitive tasks more than analytical ones", dimension: "system1" },
  { id: 93, text: "I quickly sense which option is better", dimension: "system1" },
  { id: 94, text: "I follow my instincts even when others disagree", dimension: "system1" },
  { id: 95, text: "I prefer acting first and reviewing later", dimension: "system1" },
  { id: 96, text: "I rely on emotional insight when thinking through problems", dimension: "system1" },
  { id: 97, text: "I get strong 'gut reactions' to situations", dimension: "system1" },
  { id: 98, text: "I make choices quickly when excited", dimension: "system1" },
  { id: 99, text: "I can sense the direction to take without thinking long", dimension: "system1" },
  { id: 100, text: "I often know what to do before fully understanding the situation", dimension: "system1" },

  // ===== SYSTEM 2 – REFLECTIVE DECISION STYLE (100 QUESTIONS) =====
  // Slow, deliberate, logical, evidence-based, analytical judgment
  { id: 101, text: "I prefer thinking carefully before making decisions", dimension: "system2" },
  { id: 102, text: "I like gathering information before choosing", dimension: "system2" },
  { id: 103, text: "I evaluate pros and cons before acting", dimension: "system2" },
  { id: 104, text: "I reflect deeply on important choices", dimension: "system2" },
  { id: 105, text: "I double-check information before deciding", dimension: "system2" },
  { id: 106, text: "I prefer structured and thoughtful decision-making", dimension: "system2" },
  { id: 107, text: "I take time to analyze options", dimension: "system2" },
  { id: 108, text: "I think through consequences before acting", dimension: "system2" },
  { id: 109, text: "I plan my actions carefully", dimension: "system2" },
  { id: 110, text: "I avoid rushing into decisions", dimension: "system2" },
  { id: 111, text: "I rely on evidence more than feelings", dimension: "system2" },
  { id: 112, text: "I compare alternatives before selecting one", dimension: "system2" },
  { id: 113, text: "I prefer slow, logical thinking", dimension: "system2" },
  { id: 114, text: "I analyze risks before making decisions", dimension: "system2" },
  { id: 115, text: "I reflect on past mistakes to avoid repeating them", dimension: "system2" },
  { id: 116, text: "I think through problems step-by-step", dimension: "system2" },
  { id: 117, text: "I consider long-term outcomes before choosing", dimension: "system2" },
  { id: 118, text: "I ask questions to understand the full picture", dimension: "system2" },
  { id: 119, text: "I re-evaluate decisions when new information appears", dimension: "system2" },
  { id: 120, text: "I take time to understand details", dimension: "system2" },
  { id: 121, text: "I consider possible challenges before acting", dimension: "system2" },
  { id: 122, text: "I review information carefully", dimension: "system2" },
  { id: 123, text: "I reflect quietly before making final choices", dimension: "system2" },
  { id: 124, text: "I analyze different viewpoints before deciding", dimension: "system2" },
  { id: 125, text: "I prefer planning instead of improvising", dimension: "system2" },
  { id: 126, text: "I seek clarity before making big decisions", dimension: "system2" },
  { id: 127, text: "I rely on logic when solving problems", dimension: "system2" },
  { id: 128, text: "I like breaking decisions into smaller steps", dimension: "system2" },
  { id: 129, text: "I consider the impact of my decisions on others", dimension: "system2" },
  { id: 130, text: "I prefer thorough explanations", dimension: "system2" },
  { id: 131, text: "I avoid taking unnecessary risks", dimension: "system2" },
  { id: 132, text: "I think through decisions even in familiar situations", dimension: "system2" },
  { id: 133, text: "I review instructions before starting tasks", dimension: "system2" },
  { id: 134, text: "I reflect on why something happened", dimension: "system2" },
  { id: 135, text: "I prefer structured decision-making methods", dimension: "system2" },
  { id: 136, text: "I create backup plans before acting", dimension: "system2" },
  { id: 137, text: "I check facts before accepting information", dimension: "system2" },
  { id: 138, text: "I take time to evaluate my choices", dimension: "system2" },
  { id: 139, text: "I prefer well-planned schedules", dimension: "system2" },
  { id: 140, text: "I take decisions seriously", dimension: "system2" },
  { id: 141, text: "I like analyzing complex situations", dimension: "system2" },
  { id: 142, text: "I reflect on how my decisions align with goals", dimension: "system2" },
  { id: 143, text: "I gather multiple opinions before choosing", dimension: "system2" },
  { id: 144, text: "I evaluate long-term benefits over short-term gains", dimension: "system2" },
  { id: 145, text: "I reflect on decisions to improve future choices", dimension: "system2" },
  { id: 146, text: "I think through financial decisions carefully", dimension: "system2" },
  { id: 147, text: "I prefer clarity over spontaneity", dimension: "system2" },
  { id: 148, text: "I use logical reasoning in disagreements", dimension: "system2" },
  { id: 149, text: "I examine why certain decisions work better", dimension: "system2" },
  { id: 150, text: "I compare outcomes before selecting a solution", dimension: "system2" },
  { id: 151, text: "I self-evaluate my choices regularly", dimension: "system2" },
  { id: 152, text: "I consider ethical implications of my decisions", dimension: "system2" },
  { id: 153, text: "I think through relationship decisions carefully", dimension: "system2" },
  { id: 154, text: "I avoid decisions that feel rushed", dimension: "system2" },
  { id: 155, text: "I take time to understand instructions fully", dimension: "system2" },
  { id: 156, text: "I review alternative paths before acting", dimension: "system2" },
  { id: 157, text: "I analyze consequences in detail", dimension: "system2" },
  { id: 158, text: "I think critically about information", dimension: "system2" },
  { id: 159, text: "I check if decisions align with my values", dimension: "system2" },
  { id: 160, text: "I prefer taking notes before making choices", dimension: "system2" },
  { id: 161, text: "I rely on careful thought rather than intuition", dimension: "system2" },
  { id: 162, text: "I re-analyze situations that confuse me", dimension: "system2" },
  { id: 163, text: "I use lists or written steps to decide", dimension: "system2" },
  { id: 164, text: "I prefer reviewing options with others", dimension: "system2" },
  { id: 165, text: "I avoid emotional decisions", dimension: "system2" },
  { id: 166, text: "I think slowly to avoid mistakes", dimension: "system2" },
  { id: 167, text: "I evaluate the logic behind suggestions", dimension: "system2" },
  { id: 168, text: "I analyze patterns before making predictions", dimension: "system2" },
  { id: 169, text: "I take time to understand complex issues", dimension: "system2" },
  { id: 170, text: "I reflect quietly before responding in conflicts", dimension: "system2" },
  { id: 171, text: "I re-check calculations or estimates", dimension: "system2" },
  { id: 172, text: "I compare different sources of information", dimension: "system2" },
  { id: 173, text: "I ask clarifying questions in uncertain situations", dimension: "system2" },
  { id: 174, text: "I think through strategies before acting", dimension: "system2" },
  { id: 175, text: "I reflect after tasks to learn from them", dimension: "system2" },
  { id: 176, text: "I evaluate what went well and what didn't", dimension: "system2" },
  { id: 177, text: "I prefer decisions that are fully thought out", dimension: "system2" },
  { id: 178, text: "I consider multiple scenarios for decisions", dimension: "system2" },
  { id: 179, text: "I think long-term rather than short-term", dimension: "system2" },
  { id: 180, text: "I carefully plan before starting new projects", dimension: "system2" },
  { id: 181, text: "I avoid decisions made under pressure", dimension: "system2" },
  { id: 182, text: "I analyze how one decision affects other choices", dimension: "system2" },
  { id: 183, text: "I revisit decisions to evaluate their effectiveness", dimension: "system2" },
  { id: 184, text: "I use structured tools like lists or diagrams", dimension: "system2" },
  { id: 185, text: "I consider all information available", dimension: "system2" },
  { id: 186, text: "I think deeply about major life decisions", dimension: "system2" },
  { id: 187, text: "I prefer taking time before responding in discussions", dimension: "system2" },
  { id: 188, text: "I evaluate decisions based on logic, not impulse", dimension: "system2" },
  { id: 189, text: "I reflect on how decisions align with personal goals", dimension: "system2" },
  { id: 190, text: "I think through problems instead of guessing", dimension: "system2" },
  { id: 191, text: "I reflect on what I learned from each decision", dimension: "system2" },
  { id: 192, text: "I study instructions to avoid mistakes", dimension: "system2" },
  { id: 193, text: "I organize information before deciding", dimension: "system2" },
  { id: 194, text: "I reflect before taking emotional actions", dimension: "system2" },
  { id: 195, text: "I break down complex decisions into smaller parts", dimension: "system2" },
  { id: 196, text: "I consider different outcomes before choosing", dimension: "system2" },
  { id: 197, text: "I evaluate which option is safest or most reliable", dimension: "system2" },
  { id: 198, text: "I plan the best strategy to solve issues", dimension: "system2" },
  { id: 199, text: "I take responsibility for the outcomes of my decisions", dimension: "system2" },
  { id: 200, text: "I feel more confident when decisions are well thought through", dimension: "system2" },
];
