import { Question } from '../types';

export const teachingStyleQuestions: (Question & { section: string })[] = [
  // SECTION A – Teaching Orientation (Teacher-centered vs Student-centered)
  { id: 1, text: "I see my main role as delivering content clearly to students.", dimension: "Authority", section: "A" },
  { id: 2, text: "Students should mostly listen, take notes, and follow instructions.", dimension: "Authority", section: "A" },
  { id: 3, text: "I design lessons where students discover ideas for themselves.", dimension: "Facilitation", section: "A" },
  { id: 4, text: "I prefer students to discuss, debate, and question during lessons.", dimension: "Facilitation", section: "A" },
  { id: 5, text: "I encourage students to take responsibility for their own learning.", dimension: "Facilitation", section: "A" },
  { id: 6, text: "I feel uncomfortable when lessons are noisy or unpredictable.", dimension: "Authority", section: "A" },
  { id: 7, text: "I enjoy facilitating rather than lecturing.", dimension: "Facilitation", section: "A" },
  { id: 8, text: "I believe learning happens best when students are actively involved.", dimension: "Facilitation", section: "A" },

  // SECTION B – Instructional Style (How lessons are delivered)
  { id: 9, text: "I mostly teach using explanations and examples.", dimension: "Transmission", section: "B" },
  { id: 10, text: "I often use demonstrations, models, or visual aids.", dimension: "Transmission", section: "B" },
  { id: 11, text: "I include hands-on activities or experiments in my lessons.", dimension: "Construction", section: "B" },
  { id: 12, text: "I use storytelling, real-life examples, or case studies.", dimension: "Construction", section: "B" },
  { id: 13, text: "I give students tasks to solve in groups.", dimension: "Construction", section: "B" },
  { id: 14, text: "I prefer structured lessons with clear steps.", dimension: "Transmission", section: "B" },
  { id: 15, text: "I like flexible lessons that change based on student responses.", dimension: "Construction", section: "B" },
  { id: 16, text: "I use technology (videos, slides, apps, simulations) to teach.", dimension: "Construction", section: "B" },

  // SECTION C – Classroom Control & Management
  { id: 17, text: "I keep strict control of the classroom.", dimension: "Authority", section: "C" },
  { id: 18, text: "I allow students to express themselves freely.", dimension: "Facilitation", section: "C" },
  { id: 19, text: "I set clear rules and expect students to follow them.", dimension: "Authority", section: "C" },
  { id: 20, text: "I involve students in setting classroom expectations.", dimension: "Facilitation", section: "C" },
  { id: 21, text: "I handle discipline issues firmly and quickly.", dimension: "Authority", section: "C" },
  { id: 22, text: "I prefer resolving discipline issues through discussion.", dimension: "Facilitation", section: "C" },
  { id: 23, text: "A quiet class means students are learning.", dimension: "Authority", section: "C" },
  { id: 24, text: "An active class means students are learning.", dimension: "Facilitation", section: "C" },

  // SECTION D – Student Engagement & Motivation
  { id: 25, text: "I motivate students mainly through grades and tests.", dimension: "Extrinsic", section: "D" },
  { id: 26, text: "I motivate students by making lessons interesting and relevant.", dimension: "Intrinsic", section: "D" },
  { id: 27, text: "I praise effort as much as achievement.", dimension: "Intrinsic", section: "D" },
  { id: 28, text: "I challenge high-performing students with extra tasks.", dimension: "Intrinsic", section: "D" },
  { id: 29, text: "I give extra support to struggling students.", dimension: "Intrinsic", section: "D" },
  { id: 30, text: "I use competition to motivate students.", dimension: "Extrinsic", section: "D" },
  { id: 31, text: "I use collaboration to motivate students.", dimension: "Intrinsic", section: "D" },
  { id: 32, text: "I connect lessons to students’ real lives.", dimension: "Intrinsic", section: "D" },

  // SECTION E – Assessment & Feedback Style
  { id: 33, text: "I rely mostly on exams and quizzes to assess learning.", dimension: "Judgment", section: "E" },
  { id: 34, text: "I use projects, presentations, or portfolios.", dimension: "Growth", section: "E" },
  { id: 35, text: "I give written feedback on student work.", dimension: "Growth", section: "E" },
  { id: 36, text: "I give verbal feedback during lessons.", dimension: "Growth", section: "E" },
  { id: 37, text: "I correct mistakes immediately.", dimension: "Judgment", section: "E" },
  { id: 38, text: "I allow students to learn from mistakes first.", dimension: "Growth", section: "E" },
  { id: 39, text: "I use assessment to rank students.", dimension: "Judgment", section: "E" },
  { id: 40, text: "I use assessment to guide improvement.", dimension: "Growth", section: "E" },

  // SECTION F – Adaptability & Differentiation
  { id: 41, text: "I teach all students in mostly the same way.", dimension: "Fixed", section: "F" },
  { id: 42, text: "I change how I teach based on student ability.", dimension: "Adaptive", section: "F" },
  { id: 43, text: "I provide different tasks for different learners.", dimension: "Adaptive", section: "F" },
  { id: 44, text: "I adapt lessons when students are confused.", dimension: "Adaptive", section: "F" },
  { id: 45, text: "I feel comfortable trying new teaching methods.", dimension: "Adaptive", section: "F" },
  { id: 46, text: "I prefer to stick to methods I already know work.", dimension: "Fixed", section: "F" },
  { id: 47, text: "I modify lessons for slow learners.", dimension: "Adaptive", section: "F" },
  { id: 48, text: "I extend lessons for fast learners.", dimension: "Adaptive", section: "F" },

  // SECTION G – Relationship & Emotional Climate
  { id: 49, text: "I keep a professional distance from students.", dimension: "FearBased", section: "G" },
  { id: 50, text: "I try to know my students personally.", dimension: "Safe", section: "G" },
  { id: 51, text: "I believe trust improves learning.", dimension: "Safe", section: "G" },
  { id: 52, text: "I focus mainly on academic performance.", dimension: "FearBased", section: "G" },
  { id: 53, text: "I care about students’ emotional well-being.", dimension: "Safe", section: "G" },
  { id: 54, text: "I am approachable outside class.", dimension: "Safe", section: "G" },
  { id: 55, text: "Students feel safe to ask questions in my class.", dimension: "Safe", section: "G" },
  { id: 56, text: "Students are afraid of making mistakes in my class.", dimension: "FearBased", section: "G" },

  // SECTION H – Innovation & Growth
  { id: 57, text: "I attend training to improve my teaching.", dimension: "Growth", section: "H" },
  { id: 58, text: "I reflect on what worked and what didn’t after lessons.", dimension: "Growth", section: "H" },
  { id: 59, text: "I seek feedback from students.", dimension: "Growth", section: "H" },
  { id: 60, text: "I am open to coaching and mentoring.", dimension: "Growth", section: "H" },
  { id: 61, text: "I use data (test scores, behaviour, attendance) to improve teaching.", dimension: "Growth", section: "H" },
  { id: 62, text: "I like experimenting with new strategies.", dimension: "Innovation", section: "H" },
  { id: 63, text: "I learn from other teachers.", dimension: "Growth", section: "H" },
  { id: 64, text: "I actively try to improve my teaching every term.", dimension: "Growth", section: "H" },

  // Additional Sections (Gap 65-90 skipped as per user input)

  // SECTION J? (Continued/New)
  { id: 91, text: "I value speed of response in class discussions.", dimension: "Transmission", section: "J" },
  { id: 92, text: "I model critical thinking during lessons.", dimension: "Construction", section: "J" },

  // SECTION K – Student Autonomy & Ownership (Q93–Q106)
  { id: 93, text: "I allow students to choose how they complete some tasks.", dimension: "Facilitation", section: "K" },
  { id: 94, text: "I involve students in setting learning goals.", dimension: "Facilitation", section: "K" },
  { id: 95, text: "I expect students to depend on me for instructions.", dimension: "Authority", section: "K" },
  { id: 96, text: "I encourage students to track their own progress.", dimension: "Facilitation", section: "K" },
  { id: 97, text: "I trust students to manage group work responsibly.", dimension: "Facilitation", section: "K" },
  { id: 98, text: "I intervene quickly when students struggle independently.", dimension: "Authority", section: "K" },
  { id: 99, text: "I teach students how to learn, not just what to learn.", dimension: "Facilitation", section: "K" },
  { id: 100, text: "I give students opportunities to self-assess.", dimension: "Facilitation", section: "K" },
  { id: 101, text: "I allow students to learn from failure.", dimension: "Facilitation", section: "K" },
  { id: 102, text: "I prefer to correct mistakes before they become habits.", dimension: "Authority", section: "K" },
  { id: 103, text: "I promote independent study skills.", dimension: "Facilitation", section: "K" },
  { id: 104, text: "I expect students to take initiative in learning.", dimension: "Facilitation", section: "K" },
  { id: 105, text: "I feel uneasy when students work without close supervision.", dimension: "Authority", section: "K" },
  { id: 106, text: "I encourage students to reflect on their learning strategies.", dimension: "Facilitation", section: "K" },

  // SECTION L – Inclusion, Equity & Differentiation (Q107–Q120)
  { id: 107, text: "I adapt lessons to accommodate students with learning difficulties.", dimension: "Adaptive", section: "L" },
  { id: 108, text: "I ensure all students get a chance to participate.", dimension: "Adaptive", section: "L" },
  { id: 109, text: "I tend to focus more on high-performing students.", dimension: "Fixed", section: "L" },
  { id: 110, text: "I modify teaching methods for diverse learning needs.", dimension: "Adaptive", section: "L" },
  { id: 111, text: "I consider cultural background when teaching examples.", dimension: "Adaptive", section: "L" },
  { id: 112, text: "I adjust expectations for students with different abilities.", dimension: "Adaptive", section: "L" },
  { id: 113, text: "I treat all students exactly the same regardless of needs.", dimension: "Fixed", section: "L" },
  { id: 114, text: "I create opportunities for quieter students to contribute.", dimension: "Adaptive", section: "L" },
  { id: 115, text: "I vary teaching methods to reach all learners.", dimension: "Adaptive", section: "L" },
  { id: 116, text: "I believe some students are naturally less capable.", dimension: "Fixed", section: "L" },
  { id: 117, text: "I intentionally support students who lack confidence.", dimension: "Adaptive", section: "L" },
  { id: 118, text: "I design activities that include different strengths.", dimension: "Adaptive", section: "L" },
  { id: 119, text: "I feel confident teaching mixed-ability classes.", dimension: "Adaptive", section: "L" },
  { id: 120, text: "I see diversity as an asset in the classroom.", dimension: "Adaptive", section: "L" },

  // SECTION M – Feedback, Coaching & Growth (Q121–Q134)
  { id: 121, text: "I provide feedback that helps students improve, not just score.", dimension: "Growth", section: "M" },
  { id: 122, text: "I explain how students can improve, not just what is wrong.", dimension: "Growth", section: "M" },
  { id: 123, text: "I focus feedback mainly on grades.", dimension: "Judgment", section: "M" },
  { id: 124, text: "I tailor feedback to individual students.", dimension: "Growth", section: "M" },
  { id: 125, text: "I use mistakes as learning opportunities.", dimension: "Growth", section: "M" },
  { id: 126, text: "I give feedback promptly.", dimension: "Growth", section: "M" },
  { id: 127, text: "I believe too much feedback can confuse students.", dimension: "Judgment", section: "M" },
  { id: 128, text: "I ask students to reflect on feedback received.", dimension: "Growth", section: "M" },
  { id: 129, text: "I coach students through learning challenges.", dimension: "Growth", section: "M" },
  { id: 130, text: "I prefer written feedback over verbal feedback.", dimension: "Transmission", section: "M" },
  { id: 131, text: "I monitor whether students apply feedback.", dimension: "Growth", section: "M" },
  { id: 132, text: "I encourage peer feedback.", dimension: "Growth", section: "M" },
  { id: 133, text: "I believe feedback motivates learning.", dimension: "Growth", section: "M" },
  { id: 134, text: "I adapt teaching based on assessment feedback.", dimension: "Adaptive", section: "M" },

  // SECTION N – Professional Identity & Mindset (Q135–Q164)
  { id: 135, text: "I see teaching as a craft that requires constant improvement.", dimension: "Innovation", section: "N" },
  { id: 136, text: "I reflect on my teaching regularly.", dimension: "Innovation", section: "N" },
  { id: 137, text: "I am confident in my teaching ability.", dimension: "Safe", section: "N" },
  { id: 138, text: "I believe good teaching can be learned.", dimension: "Growth", section: "N" },
  { id: 139, text: "I am open to changing long-held teaching beliefs.", dimension: "Innovation", section: "N" },
  { id: 140, text: "I seek evidence before changing my teaching methods.", dimension: "Fixed", section: "N" },
  { id: 141, text: "I believe experience matters more than training.", dimension: "Fixed", section: "N" },
  { id: 142, text: "I learn from observing other teachers.", dimension: "Innovation", section: "N" },
  { id: 143, text: "I feel responsible for students’ learning outcomes.", dimension: "Authority", section: "N" },
  { id: 144, text: "I adapt my teaching when students underperform.", dimension: "Adaptive", section: "N" },
  { id: 145, text: "I believe some students cannot be helped much.", dimension: "Fixed", section: "N" },
  { id: 146, text: "I see student failure as feedback on my teaching.", dimension: "Growth", section: "N" },
  { id: 147, text: "I feel energized by teaching challenges.", dimension: "Innovation", section: "N" },
  { id: 148, text: "I feel stressed by changes in teaching expectations.", dimension: "FearBased", section: "N" },
  { id: 149, text: "I see professional development as valuable.", dimension: "Innovation", section: "N" },
  { id: 150, text: "I take responsibility for improving my classroom practice.", dimension: "Growth", section: "N" },
  { id: 151, text: "I believe teaching styles should evolve over time.", dimension: "Innovation", section: "N" },
  { id: 152, text: "I actively seek teaching resources.", dimension: "Innovation", section: "N" },
  { id: 153, text: "I enjoy learning new teaching strategies.", dimension: "Innovation", section: "N" },
  { id: 154, text: "I see teaching as a lifelong learning process.", dimension: "Innovation", section: "N" },
  { id: 155, text: "I feel accountable for classroom climate.", dimension: "Safe", section: "N" },
  { id: 156, text: "I believe relationships matter as much as content.", dimension: "Safe", section: "N" },
  { id: 157, text: "I reflect on my emotional impact on students.", dimension: "Safe", section: "N" },
  { id: 158, text: "I believe discipline supports learning.", dimension: "Authority", section: "N" },
  { id: 159, text: "I balance authority with empathy.", dimension: "Safe", section: "N" },
  { id: 160, text: "I adjust my leadership style based on class dynamics.", dimension: "Adaptive", section: "N" },
  { id: 161, text: "I believe motivation is part of my role.", dimension: "Intrinsic", section: "N" },
  { id: 162, text: "I see myself as a learning guide.", dimension: "Facilitation", section: "N" },
  { id: 163, text: "I believe teaching shapes students beyond academics.", dimension: "Construction", section: "N" },
  { id: 164, text: "I take pride in my teaching identity.", dimension: "Intrinsic", section: "N" }
];
